// Code generated by logcopter-gen; DO NOT EDIT.

package overlay

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.pinocchio.pkg.tui.widgets.overlay")
