// Code generated by logcopter-gen; DO NOT EDIT.

package frontendtools

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.pinocchio.pkg.chatapp.frontendtools")
