// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/sem/team/team_selection.proto

package team

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payload for team member messages
type TeamMemberPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PersonId      string                 `protobuf:"bytes,2,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"` // resolved by backend, not provided by LLM
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	RoleText      string                 `protobuf:"bytes,5,opt,name=role_text,json=roleText,proto3" json:"role_text,omitempty"`
	Score         float64                `protobuf:"fixed64,6,opt,name=score,proto3" json:"score,omitempty"` // optional by presence (0 means unset)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamMemberPayload) Reset() {
	*x = TeamMemberPayload{}
	mi := &file_proto_sem_team_team_selection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamMemberPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamMemberPayload) ProtoMessage() {}

func (x *TeamMemberPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_team_team_selection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamMemberPayload.ProtoReflect.Descriptor instead.
func (*TeamMemberPayload) Descriptor() ([]byte, []int) {
	return file_proto_sem_team_team_selection_proto_rawDescGZIP(), []int{0}
}

func (x *TeamMemberPayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TeamMemberPayload) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *TeamMemberPayload) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TeamMemberPayload) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TeamMemberPayload) GetRoleText() string {
	if x != nil {
		return x.RoleText
	}
	return ""
}

func (x *TeamMemberPayload) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type TeamMemberAdded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Data          *TeamMemberPayload     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamMemberAdded) Reset() {
	*x = TeamMemberAdded{}
	mi := &file_proto_sem_team_team_selection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamMemberAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamMemberAdded) ProtoMessage() {}

func (x *TeamMemberAdded) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_team_team_selection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamMemberAdded.ProtoReflect.Descriptor instead.
func (*TeamMemberAdded) Descriptor() ([]byte, []int) {
	return file_proto_sem_team_team_selection_proto_rawDescGZIP(), []int{1}
}

func (x *TeamMemberAdded) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *TeamMemberAdded) GetData() *TeamMemberPayload {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_sem_team_team_selection_proto protoreflect.FileDescriptor

const file_proto_sem_team_team_selection_proto_rawDesc = "" +
	"\n" +
	"#proto/sem/team/team_selection.proto\x12\x17sem.team.team_selection\"\xa1\x01\n" +
	"\x11TeamMemberPayload\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tperson_id\x18\x02 \x01(\tR\bpersonId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1b\n" +
	"\trole_text\x18\x05 \x01(\tR\broleText\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x01R\x05score\"j\n" +
	"\x0fTeamMemberAdded\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12>\n" +
	"\x04data\x18\x02 \x01(\v2*.sem.team.team_selection.TeamMemberPayloadR\x04dataBBZ@github.com/go-go-golems/pinocchio/pkg/sem/pb/proto/sem/team;teamb\x06proto3"

var (
	file_proto_sem_team_team_selection_proto_rawDescOnce sync.Once
	file_proto_sem_team_team_selection_proto_rawDescData []byte
)

func file_proto_sem_team_team_selection_proto_rawDescGZIP() []byte {
	file_proto_sem_team_team_selection_proto_rawDescOnce.Do(func() {
		file_proto_sem_team_team_selection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sem_team_team_selection_proto_rawDesc), len(file_proto_sem_team_team_selection_proto_rawDesc)))
	})
	return file_proto_sem_team_team_selection_proto_rawDescData
}

var file_proto_sem_team_team_selection_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sem_team_team_selection_proto_goTypes = []any{
	(*TeamMemberPayload)(nil), // 0: sem.team.team_selection.TeamMemberPayload
	(*TeamMemberAdded)(nil),   // 1: sem.team.team_selection.TeamMemberAdded
}
var file_proto_sem_team_team_selection_proto_depIdxs = []int32{
	0, // 0: sem.team.team_selection.TeamMemberAdded.data:type_name -> sem.team.team_selection.TeamMemberPayload
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_sem_team_team_selection_proto_init() }
func file_proto_sem_team_team_selection_proto_init() {
	if File_proto_sem_team_team_selection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sem_team_team_selection_proto_rawDesc), len(file_proto_sem_team_team_selection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sem_team_team_selection_proto_goTypes,
		DependencyIndexes: file_proto_sem_team_team_selection_proto_depIdxs,
		MessageInfos:      file_proto_sem_team_team_selection_proto_msgTypes,
	}.Build()
	File_proto_sem_team_team_selection_proto = out.File
	file_proto_sem_team_team_selection_proto_goTypes = nil
	file_proto_sem_team_team_selection_proto_depIdxs = nil
}
