// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/sem/domain/team_analysis.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TeamAnalysisStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId    string                 `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	TeamSize      int32                  `protobuf:"varint,2,opt,name=team_size,json=teamSize,proto3" json:"team_size,omitempty"`
	Depth         string                 `protobuf:"bytes,3,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamAnalysisStart) Reset() {
	*x = TeamAnalysisStart{}
	mi := &file_proto_sem_domain_team_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamAnalysisStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamAnalysisStart) ProtoMessage() {}

func (x *TeamAnalysisStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_domain_team_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamAnalysisStart.ProtoReflect.Descriptor instead.
func (*TeamAnalysisStart) Descriptor() ([]byte, []int) {
	return file_proto_sem_domain_team_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *TeamAnalysisStart) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *TeamAnalysisStart) GetTeamSize() int32 {
	if x != nil {
		return x.TeamSize
	}
	return 0
}

func (x *TeamAnalysisStart) GetDepth() string {
	if x != nil {
		return x.Depth
	}
	return ""
}

type TeamAnalysisProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId    string                 `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	Analyzing     string                 `protobuf:"bytes,2,opt,name=analyzing,proto3" json:"analyzing,omitempty"`
	Progress      float64                `protobuf:"fixed64,3,opt,name=progress,proto3" json:"progress,omitempty"`
	Processed     int32                  `protobuf:"varint,4,opt,name=processed,proto3" json:"processed,omitempty"`
	Total         int32                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamAnalysisProgress) Reset() {
	*x = TeamAnalysisProgress{}
	mi := &file_proto_sem_domain_team_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamAnalysisProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamAnalysisProgress) ProtoMessage() {}

func (x *TeamAnalysisProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_domain_team_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamAnalysisProgress.ProtoReflect.Descriptor instead.
func (*TeamAnalysisProgress) Descriptor() ([]byte, []int) {
	return file_proto_sem_domain_team_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *TeamAnalysisProgress) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *TeamAnalysisProgress) GetAnalyzing() string {
	if x != nil {
		return x.Analyzing
	}
	return ""
}

func (x *TeamAnalysisProgress) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TeamAnalysisProgress) GetProcessed() int32 {
	if x != nil {
		return x.Processed
	}
	return 0
}

func (x *TeamAnalysisProgress) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type TeamAnalysisResult struct {
	state             protoimpl.MessageState                `protogen:"open.v1"`
	AnalysisId        string                                `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	NetworkScore      float64                               `protobuf:"fixed64,2,opt,name=network_score,json=networkScore,proto3" json:"network_score,omitempty"`
	Insights          []string                              `protobuf:"bytes,3,rep,name=insights,proto3" json:"insights,omitempty"`
	VisualizationData *TeamAnalysisResult_VisualizationData `protobuf:"bytes,10,opt,name=visualization_data,json=visualizationData,proto3" json:"visualization_data,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TeamAnalysisResult) Reset() {
	*x = TeamAnalysisResult{}
	mi := &file_proto_sem_domain_team_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamAnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamAnalysisResult) ProtoMessage() {}

func (x *TeamAnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_domain_team_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamAnalysisResult.ProtoReflect.Descriptor instead.
func (*TeamAnalysisResult) Descriptor() ([]byte, []int) {
	return file_proto_sem_domain_team_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *TeamAnalysisResult) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *TeamAnalysisResult) GetNetworkScore() float64 {
	if x != nil {
		return x.NetworkScore
	}
	return 0
}

func (x *TeamAnalysisResult) GetInsights() []string {
	if x != nil {
		return x.Insights
	}
	return nil
}

func (x *TeamAnalysisResult) GetVisualizationData() *TeamAnalysisResult_VisualizationData {
	if x != nil {
		return x.VisualizationData
	}
	return nil
}

type TeamAnalysisResult_Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamAnalysisResult_Node) Reset() {
	*x = TeamAnalysisResult_Node{}
	mi := &file_proto_sem_domain_team_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamAnalysisResult_Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamAnalysisResult_Node) ProtoMessage() {}

func (x *TeamAnalysisResult_Node) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_domain_team_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamAnalysisResult_Node.ProtoReflect.Descriptor instead.
func (*TeamAnalysisResult_Node) Descriptor() ([]byte, []int) {
	return file_proto_sem_domain_team_analysis_proto_rawDescGZIP(), []int{2, 0}
}

func (x *TeamAnalysisResult_Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TeamAnalysisResult_Node) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type TeamAnalysisResult_Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Strength      float64                `protobuf:"fixed64,3,opt,name=strength,proto3" json:"strength,omitempty"`
	Sentiment     string                 `protobuf:"bytes,4,opt,name=sentiment,proto3" json:"sentiment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamAnalysisResult_Edge) Reset() {
	*x = TeamAnalysisResult_Edge{}
	mi := &file_proto_sem_domain_team_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamAnalysisResult_Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamAnalysisResult_Edge) ProtoMessage() {}

func (x *TeamAnalysisResult_Edge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_domain_team_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamAnalysisResult_Edge.ProtoReflect.Descriptor instead.
func (*TeamAnalysisResult_Edge) Descriptor() ([]byte, []int) {
	return file_proto_sem_domain_team_analysis_proto_rawDescGZIP(), []int{2, 1}
}

func (x *TeamAnalysisResult_Edge) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TeamAnalysisResult_Edge) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TeamAnalysisResult_Edge) GetStrength() float64 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *TeamAnalysisResult_Edge) GetSentiment() string {
	if x != nil {
		return x.Sentiment
	}
	return ""
}

type TeamAnalysisResult_VisualizationData struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Nodes         []*TeamAnalysisResult_Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*TeamAnalysisResult_Edge `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamAnalysisResult_VisualizationData) Reset() {
	*x = TeamAnalysisResult_VisualizationData{}
	mi := &file_proto_sem_domain_team_analysis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamAnalysisResult_VisualizationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamAnalysisResult_VisualizationData) ProtoMessage() {}

func (x *TeamAnalysisResult_VisualizationData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_domain_team_analysis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamAnalysisResult_VisualizationData.ProtoReflect.Descriptor instead.
func (*TeamAnalysisResult_VisualizationData) Descriptor() ([]byte, []int) {
	return file_proto_sem_domain_team_analysis_proto_rawDescGZIP(), []int{2, 2}
}

func (x *TeamAnalysisResult_VisualizationData) GetNodes() []*TeamAnalysisResult_Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *TeamAnalysisResult_VisualizationData) GetEdges() []*TeamAnalysisResult_Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

var File_proto_sem_domain_team_analysis_proto protoreflect.FileDescriptor

const file_proto_sem_domain_team_analysis_proto_rawDesc = "" +
	"\n" +
	"$proto/sem/domain/team_analysis.proto\x12\x18sem.domain.team_analysis\"g\n" +
	"\x11TeamAnalysisStart\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\x12\x1b\n" +
	"\tteam_size\x18\x02 \x01(\x05R\bteamSize\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\tR\x05depth\"\xa5\x01\n" +
	"\x14TeamAnalysisProgress\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\x12\x1c\n" +
	"\tanalyzing\x18\x02 \x01(\tR\tanalyzing\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x01R\bprogress\x12\x1c\n" +
	"\tprocessed\x18\x04 \x01(\x05R\tprocessed\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x05R\x05total\"\xad\x04\n" +
	"\x12TeamAnalysisResult\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\x12#\n" +
	"\rnetwork_score\x18\x02 \x01(\x01R\fnetworkScore\x12\x1a\n" +
	"\binsights\x18\x03 \x03(\tR\binsights\x12m\n" +
	"\x12visualization_data\x18\n" +
	" \x01(\v2>.sem.domain.team_analysis.TeamAnalysisResult.VisualizationDataR\x11visualizationData\x1a,\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x1ap\n" +
	"\x04Edge\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1a\n" +
	"\bstrength\x18\x03 \x01(\x01R\bstrength\x12\x1c\n" +
	"\tsentiment\x18\x04 \x01(\tR\tsentiment\x1a\xa5\x01\n" +
	"\x11VisualizationData\x12G\n" +
	"\x05nodes\x18\x01 \x03(\v21.sem.domain.team_analysis.TeamAnalysisResult.NodeR\x05nodes\x12G\n" +
	"\x05edges\x18\x02 \x03(\v21.sem.domain.team_analysis.TeamAnalysisResult.EdgeR\x05edgesBFZDgithub.com/go-go-golems/pinocchio/pkg/sem/pb/proto/sem/domain;domainb\x06proto3"

var (
	file_proto_sem_domain_team_analysis_proto_rawDescOnce sync.Once
	file_proto_sem_domain_team_analysis_proto_rawDescData []byte
)

func file_proto_sem_domain_team_analysis_proto_rawDescGZIP() []byte {
	file_proto_sem_domain_team_analysis_proto_rawDescOnce.Do(func() {
		file_proto_sem_domain_team_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sem_domain_team_analysis_proto_rawDesc), len(file_proto_sem_domain_team_analysis_proto_rawDesc)))
	})
	return file_proto_sem_domain_team_analysis_proto_rawDescData
}

var file_proto_sem_domain_team_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_sem_domain_team_analysis_proto_goTypes = []any{
	(*TeamAnalysisStart)(nil),                    // 0: sem.domain.team_analysis.TeamAnalysisStart
	(*TeamAnalysisProgress)(nil),                 // 1: sem.domain.team_analysis.TeamAnalysisProgress
	(*TeamAnalysisResult)(nil),                   // 2: sem.domain.team_analysis.TeamAnalysisResult
	(*TeamAnalysisResult_Node)(nil),              // 3: sem.domain.team_analysis.TeamAnalysisResult.Node
	(*TeamAnalysisResult_Edge)(nil),              // 4: sem.domain.team_analysis.TeamAnalysisResult.Edge
	(*TeamAnalysisResult_VisualizationData)(nil), // 5: sem.domain.team_analysis.TeamAnalysisResult.VisualizationData
}
var file_proto_sem_domain_team_analysis_proto_depIdxs = []int32{
	5, // 0: sem.domain.team_analysis.TeamAnalysisResult.visualization_data:type_name -> sem.domain.team_analysis.TeamAnalysisResult.VisualizationData
	3, // 1: sem.domain.team_analysis.TeamAnalysisResult.VisualizationData.nodes:type_name -> sem.domain.team_analysis.TeamAnalysisResult.Node
	4, // 2: sem.domain.team_analysis.TeamAnalysisResult.VisualizationData.edges:type_name -> sem.domain.team_analysis.TeamAnalysisResult.Edge
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_sem_domain_team_analysis_proto_init() }
func file_proto_sem_domain_team_analysis_proto_init() {
	if File_proto_sem_domain_team_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sem_domain_team_analysis_proto_rawDesc), len(file_proto_sem_domain_team_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sem_domain_team_analysis_proto_goTypes,
		DependencyIndexes: file_proto_sem_domain_team_analysis_proto_depIdxs,
		MessageInfos:      file_proto_sem_domain_team_analysis_proto_msgTypes,
	}.Build()
	File_proto_sem_domain_team_analysis_proto = out.File
	file_proto_sem_domain_team_analysis_proto_goTypes = nil
	file_proto_sem_domain_team_analysis_proto_depIdxs = nil
}
