// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file proto/sem/base/log.proto (package sem.base.log, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/sem/base/log.proto.
 */
export const file_proto_sem_base_log: GenFile = /*@__PURE__*/
  fileDesc("Chhwcm90by9zZW0vYmFzZS9sb2cucHJvdG8SDHNlbS5iYXNlLmxvZyJcCgVMb2dWMRIKCgJpZBgBIAEoCRINCgVsZXZlbBgCIAEoCRIPCgdtZXNzYWdlGAMgASgJEicKBmZpZWxkcxgEIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3RCQlpAZ2l0aHViLmNvbS9nby1nby1nb2xlbXMvcGlub2NjaGlvL3BrZy9zZW0vcGIvcHJvdG8vc2VtL2Jhc2U7YmFzZWIGcHJvdG8z", [file_google_protobuf_struct]);

/**
 * @generated from message sem.base.log.LogV1
 */
export type LogV1 = Message<"sem.base.log.LogV1"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string level = 2;
   */
  level: string;

  /**
   * @generated from field: string message = 3;
   */
  message: string;

  /**
   * @generated from field: google.protobuf.Struct fields = 4;
   */
  fields?: JsonObject;
};

/**
 * Describes the message sem.base.log.LogV1.
 * Use `create(LogV1Schema)` to create a new message.
 */
export const LogV1Schema: GenMessage<LogV1> = /*@__PURE__*/
  messageDesc(file_proto_sem_base_log, 0);

