// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file proto/sem/base/ws.proto (package sem.base.ws, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/sem/base/ws.proto.
 */
export const file_proto_sem_base_ws: GenFile = /*@__PURE__*/
  fileDesc("Chdwcm90by9zZW0vYmFzZS93cy5wcm90bxILc2VtLmJhc2Uud3MiQgoJV3NIZWxsb1YxEg8KB2NvbnZfaWQYASABKAkSDwoHcHJvZmlsZRgCIAEoCRITCgtzZXJ2ZXJfdGltZRgDIAEoAyIwCghXc1BvbmdWMRIPCgdjb252X2lkGAEgASgJEhMKC3NlcnZlcl90aW1lGAIgASgDQkJaQGdpdGh1Yi5jb20vZ28tZ28tZ29sZW1zL3Bpbm9jY2hpby9wa2cvc2VtL3BiL3Byb3RvL3NlbS9iYXNlO2Jhc2ViBnByb3RvMw");

/**
 * @generated from message sem.base.ws.WsHelloV1
 */
export type WsHelloV1 = Message<"sem.base.ws.WsHelloV1"> & {
  /**
   * @generated from field: string conv_id = 1;
   */
  convId: string;

  /**
   * @generated from field: string profile = 2;
   */
  profile: string;

  /**
   * @generated from field: int64 server_time = 3;
   */
  serverTime: bigint;
};

/**
 * Describes the message sem.base.ws.WsHelloV1.
 * Use `create(WsHelloV1Schema)` to create a new message.
 */
export const WsHelloV1Schema: GenMessage<WsHelloV1> = /*@__PURE__*/
  messageDesc(file_proto_sem_base_ws, 0);

/**
 * @generated from message sem.base.ws.WsPongV1
 */
export type WsPongV1 = Message<"sem.base.ws.WsPongV1"> & {
  /**
   * @generated from field: string conv_id = 1;
   */
  convId: string;

  /**
   * @generated from field: int64 server_time = 2;
   */
  serverTime: bigint;
};

/**
 * Describes the message sem.base.ws.WsPongV1.
 * Use `create(WsPongV1Schema)` to create a new message.
 */
export const WsPongV1Schema: GenMessage<WsPongV1> = /*@__PURE__*/
  messageDesc(file_proto_sem_base_ws, 1);

