---
# This file contains the configuration for golangci-lint
# See https://golangci-lint.run/usage/configuration/ for reference

# Defines the configuration version.
# The only possible value is "2".
version: "2"

# Go version to use for linting
# This should match the go version in go.mod
go: "1.24"

# Linters configuration
linters:
  # Default set of linters.
  default: none
  # Enable specific linters
  enable:
    # defaults
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # additional linters
    - exhaustive
    #    - gochecknoglobals
    #    - gochecknoinits
    - nonamedreturns
    - predeclared
  # Exclusions configuration
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: 'SA1019: cli.CreateProcessorLegacy'
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - fmt.Fprintf
        - fmt.Fprintln

# Formatters configuration
formatters:
  enable:
    - gofmt
