// Code generated by logcopter-gen; DO NOT EDIT.

package profiles

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.pinocchio.cmd.web-chat.internal.profiles")
