// Code generated by logcopter-gen; DO NOT EDIT.

package pinocchio

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.pinocchio.pkg.js.modules.pinocchio")
