// Code generated by logcopter-gen; DO NOT EDIT.

package auth

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.pinocchio.cmd.pinocchio.cmds.auth")
