// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file proto/sem/timeline/message.proto (package sem.timeline, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/sem/timeline/message.proto.
 */
export const file_proto_sem_timeline_message: GenFile = /*@__PURE__*/
  fileDesc("CiBwcm90by9zZW0vdGltZWxpbmUvbWVzc2FnZS5wcm90bxIMc2VtLnRpbWVsaW5lIs8BChFNZXNzYWdlU25hcHNob3RWMRIWCg5zY2hlbWFfdmVyc2lvbhgBIAEoDRIMCgRyb2xlGAIgASgJEg8KB2NvbnRlbnQYAyABKAkSEQoJc3RyZWFtaW5nGAQgASgIEj8KCG1ldGFkYXRhGAogAygLMi0uc2VtLnRpbWVsaW5lLk1lc3NhZ2VTbmFwc2hvdFYxLk1ldGFkYXRhRW50cnkaLwoNTWV0YWRhdGFFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBQkpaSGdpdGh1Yi5jb20vZ28tZ28tZ29sZW1zL3Bpbm9jY2hpby9wa2cvc2VtL3BiL3Byb3RvL3NlbS90aW1lbGluZTt0aW1lbGluZWIGcHJvdG8z");

/**
 * MessageSnapshotV1 defines the payload for a timeline 'message' entity.
 *
 * @generated from message sem.timeline.MessageSnapshotV1
 */
export type MessageSnapshotV1 = Message<"sem.timeline.MessageSnapshotV1"> & {
  /**
   * =1
   *
   * @generated from field: uint32 schema_version = 1;
   */
  schemaVersion: number;

  /**
   * "user" | "assistant"
   *
   * @generated from field: string role = 2;
   */
  role: string;

  /**
   * Message content (aligns with TS Timeline types: props.content)
   *
   * @generated from field: string content = 3;
   */
  content: string;

  /**
   * True during streaming
   *
   * @generated from field: bool streaming = 4;
   */
  streaming: boolean;

  /**
   * Optional metadata; empty map if absent
   *
   * @generated from field: map<string, string> metadata = 10;
   */
  metadata: { [key: string]: string };
};

/**
 * Describes the message sem.timeline.MessageSnapshotV1.
 * Use `create(MessageSnapshotV1Schema)` to create a new message.
 */
export const MessageSnapshotV1Schema: GenMessage<MessageSnapshotV1> = /*@__PURE__*/
  messageDesc(file_proto_sem_timeline_message, 0);

