// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file proto/sem/timeline/planning.proto (package sem.timeline, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/sem/timeline/planning.proto.
 */
export const file_proto_sem_timeline_planning: GenFile = /*@__PURE__*/
  fileDesc("CiFwcm90by9zZW0vdGltZWxpbmUvcGxhbm5pbmcucHJvdG8SDHNlbS50aW1lbGluZSLtAQobUGxhbm5pbmdJdGVyYXRpb25TbmFwc2hvdFYxEhcKD2l0ZXJhdGlvbl9pbmRleBgBIAEoBRIOCgZhY3Rpb24YAiABKAkSEQoJcmVhc29uaW5nGAMgASgJEhAKCHN0cmF0ZWd5GAQgASgJEhAKCHByb2dyZXNzGAUgASgJEhEKCXRvb2xfbmFtZRgGIAEoCRImCgVleHRyYRgHIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3QSGgoSZW1pdHRlZF9hdF91bml4X21zGAggASgDEhcKD3JlZmxlY3Rpb25fdGV4dBgJIAEoCSKhAQoTRXhlY3V0aW9uU25hcHNob3RWMRIWCg5leGVjdXRvcl9tb2RlbBgBIAEoCRIRCglkaXJlY3RpdmUYAiABKAkSGgoSc3RhcnRlZF9hdF91bml4X21zGAMgASgDEhwKFGNvbXBsZXRlZF9hdF91bml4X21zGAQgASgDEg4KBnN0YXR1cxgFIAEoCRIVCg1lcnJvcl9tZXNzYWdlGAYgASgJIoQDChJQbGFubmluZ1NuYXBzaG90VjESFgoOc2NoZW1hX3ZlcnNpb24YASABKA0SDgoGcnVuX2lkGAIgASgJEhAKCHByb3ZpZGVyGAMgASgJEhUKDXBsYW5uZXJfbW9kZWwYBCABKAkSFgoObWF4X2l0ZXJhdGlvbnMYBSABKAUSGgoSc3RhcnRlZF9hdF91bml4X21zGAogASgDEhwKFGNvbXBsZXRlZF9hdF91bml4X21zGAsgASgDEg4KBnN0YXR1cxgMIAEoCRIWCg5maW5hbF9kZWNpc2lvbhgNIAEoCRIVCg1zdGF0dXNfcmVhc29uGA4gASgJEhcKD2ZpbmFsX2RpcmVjdGl2ZRgPIAEoCRI9CgppdGVyYXRpb25zGBQgAygLMikuc2VtLnRpbWVsaW5lLlBsYW5uaW5nSXRlcmF0aW9uU25hcHNob3RWMRI0CglleGVjdXRpb24YFSABKAsyIS5zZW0udGltZWxpbmUuRXhlY3V0aW9uU25hcHNob3RWMUJKWkhnaXRodWIuY29tL2dvLWdvLWdvbGVtcy9waW5vY2NoaW8vcGtnL3NlbS9wYi9wcm90by9zZW0vdGltZWxpbmU7dGltZWxpbmViBnByb3RvMw", [file_google_protobuf_struct]);

/**
 * @generated from message sem.timeline.PlanningIterationSnapshotV1
 */
export type PlanningIterationSnapshotV1 = Message<"sem.timeline.PlanningIterationSnapshotV1"> & {
  /**
   * 1-based
   *
   * @generated from field: int32 iteration_index = 1;
   */
  iterationIndex: number;

  /**
   * @generated from field: string action = 2;
   */
  action: string;

  /**
   * @generated from field: string reasoning = 3;
   */
  reasoning: string;

  /**
   * @generated from field: string strategy = 4;
   */
  strategy: string;

  /**
   * @generated from field: string progress = 5;
   */
  progress: string;

  /**
   * @generated from field: string tool_name = 6;
   */
  toolName: string;

  /**
   * @generated from field: google.protobuf.Struct extra = 7;
   */
  extra?: JsonObject;

  /**
   * @generated from field: int64 emitted_at_unix_ms = 8;
   */
  emittedAtUnixMs: bigint;

  /**
   * @generated from field: string reflection_text = 9;
   */
  reflectionText: string;
};

/**
 * Describes the message sem.timeline.PlanningIterationSnapshotV1.
 * Use `create(PlanningIterationSnapshotV1Schema)` to create a new message.
 */
export const PlanningIterationSnapshotV1Schema: GenMessage<PlanningIterationSnapshotV1> = /*@__PURE__*/
  messageDesc(file_proto_sem_timeline_planning, 0);

/**
 * @generated from message sem.timeline.ExecutionSnapshotV1
 */
export type ExecutionSnapshotV1 = Message<"sem.timeline.ExecutionSnapshotV1"> & {
  /**
   * @generated from field: string executor_model = 1;
   */
  executorModel: string;

  /**
   * @generated from field: string directive = 2;
   */
  directive: string;

  /**
   * @generated from field: int64 started_at_unix_ms = 3;
   */
  startedAtUnixMs: bigint;

  /**
   * @generated from field: int64 completed_at_unix_ms = 4;
   */
  completedAtUnixMs: bigint;

  /**
   * running|completed|error
   *
   * @generated from field: string status = 5;
   */
  status: string;

  /**
   * optional
   *
   * @generated from field: string error_message = 6;
   */
  errorMessage: string;
};

/**
 * Describes the message sem.timeline.ExecutionSnapshotV1.
 * Use `create(ExecutionSnapshotV1Schema)` to create a new message.
 */
export const ExecutionSnapshotV1Schema: GenMessage<ExecutionSnapshotV1> = /*@__PURE__*/
  messageDesc(file_proto_sem_timeline_planning, 1);

/**
 * PlanningSnapshotV1 defines the payload for a timeline 'planning' entity.
 *
 * @generated from message sem.timeline.PlanningSnapshotV1
 */
export type PlanningSnapshotV1 = Message<"sem.timeline.PlanningSnapshotV1"> & {
  /**
   * =1
   *
   * @generated from field: uint32 schema_version = 1;
   */
  schemaVersion: number;

  /**
   * A single planner run (correlates to sem.middleware.planning.PlanningRun.run_id).
   *
   * @generated from field: string run_id = 2;
   */
  runId: string;

  /**
   * @generated from field: string provider = 3;
   */
  provider: string;

  /**
   * @generated from field: string planner_model = 4;
   */
  plannerModel: string;

  /**
   * @generated from field: int32 max_iterations = 5;
   */
  maxIterations: number;

  /**
   * @generated from field: int64 started_at_unix_ms = 10;
   */
  startedAtUnixMs: bigint;

  /**
   * @generated from field: int64 completed_at_unix_ms = 11;
   */
  completedAtUnixMs: bigint;

  /**
   * planning|executing|completed|error
   *
   * @generated from field: string status = 12;
   */
  status: string;

  /**
   * @generated from field: string final_decision = 13;
   */
  finalDecision: string;

  /**
   * @generated from field: string status_reason = 14;
   */
  statusReason: string;

  /**
   * @generated from field: string final_directive = 15;
   */
  finalDirective: string;

  /**
   * @generated from field: repeated sem.timeline.PlanningIterationSnapshotV1 iterations = 20;
   */
  iterations: PlanningIterationSnapshotV1[];

  /**
   * @generated from field: sem.timeline.ExecutionSnapshotV1 execution = 21;
   */
  execution?: ExecutionSnapshotV1;
};

/**
 * Describes the message sem.timeline.PlanningSnapshotV1.
 * Use `create(PlanningSnapshotV1Schema)` to create a new message.
 */
export const PlanningSnapshotV1Schema: GenMessage<PlanningSnapshotV1> = /*@__PURE__*/
  messageDesc(file_proto_sem_timeline_planning, 2);

