// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file proto/sem/timeline/team_analysis.proto (package sem.timeline, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { TeamAnalysisResult_VisualizationData } from "../domain/team_analysis_pb";
import { file_proto_sem_domain_team_analysis } from "../domain/team_analysis_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/sem/timeline/team_analysis.proto.
 */
export const file_proto_sem_timeline_team_analysis: GenFile = /*@__PURE__*/
  fileDesc("CiZwcm90by9zZW0vdGltZWxpbmUvdGVhbV9hbmFseXNpcy5wcm90bxIMc2VtLnRpbWVsaW5lIvgBChZUZWFtQW5hbHlzaXNTbmFwc2hvdFYxEhYKDnNjaGVtYV92ZXJzaW9uGAEgASgNEg4KBnN0YXR1cxgCIAEoCRIRCgl0ZWFtX3NpemUYAyABKAUSDQoFZGVwdGgYBCABKAkSEAoIcHJvZ3Jlc3MYBSABKAESFAoMY3VycmVudF9wYWlyGAYgASgJEhAKCGluc2lnaHRzGAcgAygJEloKEnZpc3VhbGl6YXRpb25fZGF0YRgKIAEoCzI+LnNlbS5kb21haW4udGVhbV9hbmFseXNpcy5UZWFtQW5hbHlzaXNSZXN1bHQuVmlzdWFsaXphdGlvbkRhdGFCSlpIZ2l0aHViLmNvbS9nby1nby1nb2xlbXMvcGlub2NjaGlvL3BrZy9zZW0vcGIvcHJvdG8vc2VtL3RpbWVsaW5lO3RpbWVsaW5lYgZwcm90bzM", [file_proto_sem_domain_team_analysis]);

/**
 * TeamAnalysisSnapshotV1 defines the payload for a 'team_analysis' entity.
 *
 * @generated from message sem.timeline.TeamAnalysisSnapshotV1
 */
export type TeamAnalysisSnapshotV1 = Message<"sem.timeline.TeamAnalysisSnapshotV1"> & {
  /**
   * =1
   *
   * @generated from field: uint32 schema_version = 1;
   */
  schemaVersion: number;

  /**
   * analyzing|completed|error
   *
   * @generated from field: string status = 2;
   */
  status: string;

  /**
   * @generated from field: int32 team_size = 3;
   */
  teamSize: number;

  /**
   * @generated from field: string depth = 4;
   */
  depth: string;

  /**
   * @generated from field: double progress = 5;
   */
  progress: number;

  /**
   * @generated from field: string current_pair = 6;
   */
  currentPair: string;

  /**
   * @generated from field: repeated string insights = 7;
   */
  insights: string[];

  /**
   * Reuse VisualizationData from domain proto
   *
   * @generated from field: sem.domain.team_analysis.TeamAnalysisResult.VisualizationData visualization_data = 10;
   */
  visualizationData?: TeamAnalysisResult_VisualizationData;
};

/**
 * Describes the message sem.timeline.TeamAnalysisSnapshotV1.
 * Use `create(TeamAnalysisSnapshotV1Schema)` to create a new message.
 */
export const TeamAnalysisSnapshotV1Schema: GenMessage<TeamAnalysisSnapshotV1> = /*@__PURE__*/
  messageDesc(file_proto_sem_timeline_team_analysis, 0);

