// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file proto/sem/timeline/tool.proto (package sem.timeline, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/sem/timeline/tool.proto.
 */
export const file_proto_sem_timeline_tool: GenFile = /*@__PURE__*/
  fileDesc("Ch1wcm90by9zZW0vdGltZWxpbmUvdG9vbC5wcm90bxIMc2VtLnRpbWVsaW5lIoQBChJUb29sQ2FsbFNuYXBzaG90VjESFgoOc2NoZW1hX3ZlcnNpb24YASABKA0SDAoEbmFtZRgCIAEoCRImCgVpbnB1dBgDIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3QSDgoGc3RhdHVzGAQgASgJEhAKCHByb2dyZXNzGAUgASgBInwKFFRvb2xSZXN1bHRTbmFwc2hvdFYxEhYKDnNjaGVtYV92ZXJzaW9uGAEgASgNEhQKDHRvb2xfY2FsbF9pZBgCIAEoCRInCgZyZXN1bHQYAyABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0Eg0KBWVycm9yGAQgASgJQkpaSGdpdGh1Yi5jb20vZ28tZ28tZ29sZW1zL3Bpbm9jY2hpby9wa2cvc2VtL3BiL3Byb3RvL3NlbS90aW1lbGluZTt0aW1lbGluZWIGcHJvdG8z", [file_google_protobuf_struct]);

/**
 * ToolCallSnapshotV1 defines the payload for a 'tool_call' entity.
 *
 * @generated from message sem.timeline.ToolCallSnapshotV1
 */
export type ToolCallSnapshotV1 = Message<"sem.timeline.ToolCallSnapshotV1"> & {
  /**
   * =1
   *
   * @generated from field: uint32 schema_version = 1;
   */
  schemaVersion: number;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * structured input
   *
   * @generated from field: google.protobuf.Struct input = 3;
   */
  input?: JsonObject;

  /**
   * queued|running|completed|error
   *
   * @generated from field: string status = 4;
   */
  status: string;

  /**
   * 0..1
   *
   * @generated from field: double progress = 5;
   */
  progress: number;
};

/**
 * Describes the message sem.timeline.ToolCallSnapshotV1.
 * Use `create(ToolCallSnapshotV1Schema)` to create a new message.
 */
export const ToolCallSnapshotV1Schema: GenMessage<ToolCallSnapshotV1> = /*@__PURE__*/
  messageDesc(file_proto_sem_timeline_tool, 0);

/**
 * ToolResultSnapshotV1 defines the payload for a 'tool_result' entity.
 *
 * @generated from message sem.timeline.ToolResultSnapshotV1
 */
export type ToolResultSnapshotV1 = Message<"sem.timeline.ToolResultSnapshotV1"> & {
  /**
   * =1
   *
   * @generated from field: uint32 schema_version = 1;
   */
  schemaVersion: number;

  /**
   * -> toolCallId (camelCase) in JSON
   *
   * @generated from field: string tool_call_id = 2;
   */
  toolCallId: string;

  /**
   * structured result
   *
   * @generated from field: google.protobuf.Struct result = 3;
   */
  result?: JsonObject;

  /**
   * optional
   *
   * @generated from field: string error = 4;
   */
  error: string;
};

/**
 * Describes the message sem.timeline.ToolResultSnapshotV1.
 * Use `create(ToolResultSnapshotV1Schema)` to create a new message.
 */
export const ToolResultSnapshotV1Schema: GenMessage<ToolResultSnapshotV1> = /*@__PURE__*/
  messageDesc(file_proto_sem_timeline_tool, 1);

