// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/sem/base/llm.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LlmStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // "assistant" | "thinking"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LlmStart) Reset() {
	*x = LlmStart{}
	mi := &file_proto_sem_base_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LlmStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LlmStart) ProtoMessage() {}

func (x *LlmStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_base_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LlmStart.ProtoReflect.Descriptor instead.
func (*LlmStart) Descriptor() ([]byte, []int) {
	return file_proto_sem_base_llm_proto_rawDescGZIP(), []int{0}
}

func (x *LlmStart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LlmStart) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type LlmDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Delta         string                 `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`
	Cumulative    string                 `protobuf:"bytes,3,opt,name=cumulative,proto3" json:"cumulative,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LlmDelta) Reset() {
	*x = LlmDelta{}
	mi := &file_proto_sem_base_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LlmDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LlmDelta) ProtoMessage() {}

func (x *LlmDelta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_base_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LlmDelta.ProtoReflect.Descriptor instead.
func (*LlmDelta) Descriptor() ([]byte, []int) {
	return file_proto_sem_base_llm_proto_rawDescGZIP(), []int{1}
}

func (x *LlmDelta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LlmDelta) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *LlmDelta) GetCumulative() string {
	if x != nil {
		return x.Cumulative
	}
	return ""
}

type LlmFinal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LlmFinal) Reset() {
	*x = LlmFinal{}
	mi := &file_proto_sem_base_llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LlmFinal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LlmFinal) ProtoMessage() {}

func (x *LlmFinal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_base_llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LlmFinal.ProtoReflect.Descriptor instead.
func (*LlmFinal) Descriptor() ([]byte, []int) {
	return file_proto_sem_base_llm_proto_rawDescGZIP(), []int{2}
}

func (x *LlmFinal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LlmFinal) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type LlmDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LlmDone) Reset() {
	*x = LlmDone{}
	mi := &file_proto_sem_base_llm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LlmDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LlmDone) ProtoMessage() {}

func (x *LlmDone) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_base_llm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LlmDone.ProtoReflect.Descriptor instead.
func (*LlmDone) Descriptor() ([]byte, []int) {
	return file_proto_sem_base_llm_proto_rawDescGZIP(), []int{3}
}

func (x *LlmDone) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_sem_base_llm_proto protoreflect.FileDescriptor

const file_proto_sem_base_llm_proto_rawDesc = "" +
	"\n" +
	"\x18proto/sem/base/llm.proto\x12\fsem.base.llm\".\n" +
	"\bLlmStart\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"P\n" +
	"\bLlmDelta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\tR\x05delta\x12\x1e\n" +
	"\n" +
	"cumulative\x18\x03 \x01(\tR\n" +
	"cumulative\".\n" +
	"\bLlmFinal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x19\n" +
	"\aLlmDone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idBBZ@github.com/go-go-golems/pinocchio/pkg/sem/pb/proto/sem/base;baseb\x06proto3"

var (
	file_proto_sem_base_llm_proto_rawDescOnce sync.Once
	file_proto_sem_base_llm_proto_rawDescData []byte
)

func file_proto_sem_base_llm_proto_rawDescGZIP() []byte {
	file_proto_sem_base_llm_proto_rawDescOnce.Do(func() {
		file_proto_sem_base_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sem_base_llm_proto_rawDesc), len(file_proto_sem_base_llm_proto_rawDesc)))
	})
	return file_proto_sem_base_llm_proto_rawDescData
}

var file_proto_sem_base_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_sem_base_llm_proto_goTypes = []any{
	(*LlmStart)(nil), // 0: sem.base.llm.LlmStart
	(*LlmDelta)(nil), // 1: sem.base.llm.LlmDelta
	(*LlmFinal)(nil), // 2: sem.base.llm.LlmFinal
	(*LlmDone)(nil),  // 3: sem.base.llm.LlmDone
}
var file_proto_sem_base_llm_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sem_base_llm_proto_init() }
func file_proto_sem_base_llm_proto_init() {
	if File_proto_sem_base_llm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sem_base_llm_proto_rawDesc), len(file_proto_sem_base_llm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sem_base_llm_proto_goTypes,
		DependencyIndexes: file_proto_sem_base_llm_proto_depIdxs,
		MessageInfos:      file_proto_sem_base_llm_proto_msgTypes,
	}.Build()
	File_proto_sem_base_llm_proto = out.File
	file_proto_sem_base_llm_proto_goTypes = nil
	file_proto_sem_base_llm_proto_depIdxs = nil
}
