// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/sem/base/metadata.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsageV1 struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	InputTokens              int32                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens             int32                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CachedTokens             int32                  `protobuf:"varint,3,opt,name=cached_tokens,json=cachedTokens,proto3" json:"cached_tokens,omitempty"`
	CacheCreationInputTokens int32                  `protobuf:"varint,4,opt,name=cache_creation_input_tokens,json=cacheCreationInputTokens,proto3" json:"cache_creation_input_tokens,omitempty"`
	CacheReadInputTokens     int32                  `protobuf:"varint,5,opt,name=cache_read_input_tokens,json=cacheReadInputTokens,proto3" json:"cache_read_input_tokens,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UsageV1) Reset() {
	*x = UsageV1{}
	mi := &file_proto_sem_base_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageV1) ProtoMessage() {}

func (x *UsageV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_base_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageV1.ProtoReflect.Descriptor instead.
func (*UsageV1) Descriptor() ([]byte, []int) {
	return file_proto_sem_base_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *UsageV1) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *UsageV1) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *UsageV1) GetCachedTokens() int32 {
	if x != nil {
		return x.CachedTokens
	}
	return 0
}

func (x *UsageV1) GetCacheCreationInputTokens() int32 {
	if x != nil {
		return x.CacheCreationInputTokens
	}
	return 0
}

func (x *UsageV1) GetCacheReadInputTokens() int32 {
	if x != nil {
		return x.CacheReadInputTokens
	}
	return 0
}

type LlmInferenceMetadataV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Temperature   *float64               `protobuf:"fixed64,2,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	TopP          *float64               `protobuf:"fixed64,3,opt,name=top_p,json=topP,proto3,oneof" json:"top_p,omitempty"`
	MaxTokens     *int32                 `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3,oneof" json:"max_tokens,omitempty"`
	StopReason    *string                `protobuf:"bytes,5,opt,name=stop_reason,json=stopReason,proto3,oneof" json:"stop_reason,omitempty"`
	Usage         *UsageV1               `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	DurationMs    *int64                 `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3,oneof" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LlmInferenceMetadataV1) Reset() {
	*x = LlmInferenceMetadataV1{}
	mi := &file_proto_sem_base_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LlmInferenceMetadataV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LlmInferenceMetadataV1) ProtoMessage() {}

func (x *LlmInferenceMetadataV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_base_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LlmInferenceMetadataV1.ProtoReflect.Descriptor instead.
func (*LlmInferenceMetadataV1) Descriptor() ([]byte, []int) {
	return file_proto_sem_base_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *LlmInferenceMetadataV1) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LlmInferenceMetadataV1) GetTemperature() float64 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *LlmInferenceMetadataV1) GetTopP() float64 {
	if x != nil && x.TopP != nil {
		return *x.TopP
	}
	return 0
}

func (x *LlmInferenceMetadataV1) GetMaxTokens() int32 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

func (x *LlmInferenceMetadataV1) GetStopReason() string {
	if x != nil && x.StopReason != nil {
		return *x.StopReason
	}
	return ""
}

func (x *LlmInferenceMetadataV1) GetUsage() *UsageV1 {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *LlmInferenceMetadataV1) GetDurationMs() int64 {
	if x != nil && x.DurationMs != nil {
		return *x.DurationMs
	}
	return 0
}

var File_proto_sem_base_metadata_proto protoreflect.FileDescriptor

const file_proto_sem_base_metadata_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/sem/base/metadata.proto\x12\rsem.base.meta\"\xec\x01\n" +
	"\aUsageV1\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x05R\foutputTokens\x12#\n" +
	"\rcached_tokens\x18\x03 \x01(\x05R\fcachedTokens\x12=\n" +
	"\x1bcache_creation_input_tokens\x18\x04 \x01(\x05R\x18cacheCreationInputTokens\x125\n" +
	"\x17cache_read_input_tokens\x18\x05 \x01(\x05R\x14cacheReadInputTokens\"\xd6\x02\n" +
	"\x16LlmInferenceMetadataV1\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12%\n" +
	"\vtemperature\x18\x02 \x01(\x01H\x00R\vtemperature\x88\x01\x01\x12\x18\n" +
	"\x05top_p\x18\x03 \x01(\x01H\x01R\x04topP\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05H\x02R\tmaxTokens\x88\x01\x01\x12$\n" +
	"\vstop_reason\x18\x05 \x01(\tH\x03R\n" +
	"stopReason\x88\x01\x01\x12,\n" +
	"\x05usage\x18\x06 \x01(\v2\x16.sem.base.meta.UsageV1R\x05usage\x12$\n" +
	"\vduration_ms\x18\a \x01(\x03H\x04R\n" +
	"durationMs\x88\x01\x01B\x0e\n" +
	"\f_temperatureB\b\n" +
	"\x06_top_pB\r\n" +
	"\v_max_tokensB\x0e\n" +
	"\f_stop_reasonB\x0e\n" +
	"\f_duration_msBBZ@github.com/go-go-golems/pinocchio/pkg/sem/pb/proto/sem/base;baseb\x06proto3"

var (
	file_proto_sem_base_metadata_proto_rawDescOnce sync.Once
	file_proto_sem_base_metadata_proto_rawDescData []byte
)

func file_proto_sem_base_metadata_proto_rawDescGZIP() []byte {
	file_proto_sem_base_metadata_proto_rawDescOnce.Do(func() {
		file_proto_sem_base_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sem_base_metadata_proto_rawDesc), len(file_proto_sem_base_metadata_proto_rawDesc)))
	})
	return file_proto_sem_base_metadata_proto_rawDescData
}

var file_proto_sem_base_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sem_base_metadata_proto_goTypes = []any{
	(*UsageV1)(nil),                // 0: sem.base.meta.UsageV1
	(*LlmInferenceMetadataV1)(nil), // 1: sem.base.meta.LlmInferenceMetadataV1
}
var file_proto_sem_base_metadata_proto_depIdxs = []int32{
	0, // 0: sem.base.meta.LlmInferenceMetadataV1.usage:type_name -> sem.base.meta.UsageV1
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_sem_base_metadata_proto_init() }
func file_proto_sem_base_metadata_proto_init() {
	if File_proto_sem_base_metadata_proto != nil {
		return
	}
	file_proto_sem_base_metadata_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sem_base_metadata_proto_rawDesc), len(file_proto_sem_base_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sem_base_metadata_proto_goTypes,
		DependencyIndexes: file_proto_sem_base_metadata_proto_depIdxs,
		MessageInfos:      file_proto_sem_base_metadata_proto_msgTypes,
	}.Build()
	File_proto_sem_base_metadata_proto = out.File
	file_proto_sem_base_metadata_proto_goTypes = nil
	file_proto_sem_base_metadata_proto_depIdxs = nil
}
