// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file proto/sem/base/llm.proto (package sem.base.llm, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/sem/base/llm.proto.
 */
export const file_proto_sem_base_llm: GenFile = /*@__PURE__*/
  fileDesc("Chhwcm90by9zZW0vYmFzZS9sbG0ucHJvdG8SDHNlbS5iYXNlLmxsbSIkCghMbG1TdGFydBIKCgJpZBgBIAEoCRIMCgRyb2xlGAIgASgJIjkKCExsbURlbHRhEgoKAmlkGAEgASgJEg0KBWRlbHRhGAIgASgJEhIKCmN1bXVsYXRpdmUYAyABKAkiJAoITGxtRmluYWwSCgoCaWQYASABKAkSDAoEdGV4dBgCIAEoCSIVCgdMbG1Eb25lEgoKAmlkGAEgASgJQkJaQGdpdGh1Yi5jb20vZ28tZ28tZ29sZW1zL3Bpbm9jY2hpby9wa2cvc2VtL3BiL3Byb3RvL3NlbS9iYXNlO2Jhc2ViBnByb3RvMw");

/**
 * @generated from message sem.base.llm.LlmStart
 */
export type LlmStart = Message<"sem.base.llm.LlmStart"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * "assistant" | "thinking"
   *
   * @generated from field: string role = 2;
   */
  role: string;
};

/**
 * Describes the message sem.base.llm.LlmStart.
 * Use `create(LlmStartSchema)` to create a new message.
 */
export const LlmStartSchema: GenMessage<LlmStart> = /*@__PURE__*/
  messageDesc(file_proto_sem_base_llm, 0);

/**
 * @generated from message sem.base.llm.LlmDelta
 */
export type LlmDelta = Message<"sem.base.llm.LlmDelta"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string delta = 2;
   */
  delta: string;

  /**
   * @generated from field: string cumulative = 3;
   */
  cumulative: string;
};

/**
 * Describes the message sem.base.llm.LlmDelta.
 * Use `create(LlmDeltaSchema)` to create a new message.
 */
export const LlmDeltaSchema: GenMessage<LlmDelta> = /*@__PURE__*/
  messageDesc(file_proto_sem_base_llm, 1);

/**
 * @generated from message sem.base.llm.LlmFinal
 */
export type LlmFinal = Message<"sem.base.llm.LlmFinal"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string text = 2;
   */
  text: string;
};

/**
 * Describes the message sem.base.llm.LlmFinal.
 * Use `create(LlmFinalSchema)` to create a new message.
 */
export const LlmFinalSchema: GenMessage<LlmFinal> = /*@__PURE__*/
  messageDesc(file_proto_sem_base_llm, 2);

/**
 * @generated from message sem.base.llm.LlmDone
 */
export type LlmDone = Message<"sem.base.llm.LlmDone"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message sem.base.llm.LlmDone.
 * Use `create(LlmDoneSchema)` to create a new message.
 */
export const LlmDoneSchema: GenMessage<LlmDone> = /*@__PURE__*/
  messageDesc(file_proto_sem_base_llm, 3);

