// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file proto/sem/base/metadata.proto (package sem.base.meta, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/sem/base/metadata.proto.
 */
export const file_proto_sem_base_metadata: GenFile = /*@__PURE__*/
  fileDesc("Ch1wcm90by9zZW0vYmFzZS9tZXRhZGF0YS5wcm90bxINc2VtLmJhc2UubWV0YSKTAQoHVXNhZ2VWMRIUCgxpbnB1dF90b2tlbnMYASABKAUSFQoNb3V0cHV0X3Rva2VucxgCIAEoBRIVCg1jYWNoZWRfdG9rZW5zGAMgASgFEiMKG2NhY2hlX2NyZWF0aW9uX2lucHV0X3Rva2VucxgEIAEoBRIfChdjYWNoZV9yZWFkX2lucHV0X3Rva2VucxgFIAEoBSKSAgoWTGxtSW5mZXJlbmNlTWV0YWRhdGFWMRINCgVtb2RlbBgBIAEoCRIYCgt0ZW1wZXJhdHVyZRgCIAEoAUgAiAEBEhIKBXRvcF9wGAMgASgBSAGIAQESFwoKbWF4X3Rva2VucxgEIAEoBUgCiAEBEhgKC3N0b3BfcmVhc29uGAUgASgJSAOIAQESJQoFdXNhZ2UYBiABKAsyFi5zZW0uYmFzZS5tZXRhLlVzYWdlVjESGAoLZHVyYXRpb25fbXMYByABKANIBIgBAUIOCgxfdGVtcGVyYXR1cmVCCAoGX3RvcF9wQg0KC19tYXhfdG9rZW5zQg4KDF9zdG9wX3JlYXNvbkIOCgxfZHVyYXRpb25fbXNCQlpAZ2l0aHViLmNvbS9nby1nby1nb2xlbXMvcGlub2NjaGlvL3BrZy9zZW0vcGIvcHJvdG8vc2VtL2Jhc2U7YmFzZWIGcHJvdG8z");

/**
 * @generated from message sem.base.meta.UsageV1
 */
export type UsageV1 = Message<"sem.base.meta.UsageV1"> & {
  /**
   * @generated from field: int32 input_tokens = 1;
   */
  inputTokens: number;

  /**
   * @generated from field: int32 output_tokens = 2;
   */
  outputTokens: number;

  /**
   * @generated from field: int32 cached_tokens = 3;
   */
  cachedTokens: number;

  /**
   * @generated from field: int32 cache_creation_input_tokens = 4;
   */
  cacheCreationInputTokens: number;

  /**
   * @generated from field: int32 cache_read_input_tokens = 5;
   */
  cacheReadInputTokens: number;
};

/**
 * Describes the message sem.base.meta.UsageV1.
 * Use `create(UsageV1Schema)` to create a new message.
 */
export const UsageV1Schema: GenMessage<UsageV1> = /*@__PURE__*/
  messageDesc(file_proto_sem_base_metadata, 0);

/**
 * @generated from message sem.base.meta.LlmInferenceMetadataV1
 */
export type LlmInferenceMetadataV1 = Message<"sem.base.meta.LlmInferenceMetadataV1"> & {
  /**
   * @generated from field: string model = 1;
   */
  model: string;

  /**
   * @generated from field: optional double temperature = 2;
   */
  temperature?: number;

  /**
   * @generated from field: optional double top_p = 3;
   */
  topP?: number;

  /**
   * @generated from field: optional int32 max_tokens = 4;
   */
  maxTokens?: number;

  /**
   * @generated from field: optional string stop_reason = 5;
   */
  stopReason?: string;

  /**
   * @generated from field: sem.base.meta.UsageV1 usage = 6;
   */
  usage?: UsageV1;

  /**
   * @generated from field: optional int64 duration_ms = 7;
   */
  durationMs?: bigint;
};

/**
 * Describes the message sem.base.meta.LlmInferenceMetadataV1.
 * Use `create(LlmInferenceMetadataV1Schema)` to create a new message.
 */
export const LlmInferenceMetadataV1Schema: GenMessage<LlmInferenceMetadataV1> = /*@__PURE__*/
  messageDesc(file_proto_sem_base_metadata, 1);

