// Code generated by logcopter-gen; DO NOT EDIT.

package tools

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.pinocchio.cmd.agents.simple-chat-agent.pkg.tools")
