// Code generated by logcopter-gen; DO NOT EDIT.

package chatapprpcv1

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.pinocchio.pkg.chatapp.pb.proto.pinocchio.chatapp.rpc.v1")
