// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/sem/timeline/message.proto

package timeline

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageSnapshotV1 defines the payload for a timeline 'message' entity.
type MessageSnapshotV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // =1
	// "user" | "assistant"
	Role string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	// Message content (aligns with TS Timeline types: props.content)
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// True during streaming
	Streaming bool `protobuf:"varint,4,opt,name=streaming,proto3" json:"streaming,omitempty"`
	// Optional metadata; empty map if absent
	Metadata      map[string]string `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSnapshotV1) Reset() {
	*x = MessageSnapshotV1{}
	mi := &file_proto_sem_timeline_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSnapshotV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSnapshotV1) ProtoMessage() {}

func (x *MessageSnapshotV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_timeline_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSnapshotV1.ProtoReflect.Descriptor instead.
func (*MessageSnapshotV1) Descriptor() ([]byte, []int) {
	return file_proto_sem_timeline_message_proto_rawDescGZIP(), []int{0}
}

func (x *MessageSnapshotV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *MessageSnapshotV1) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MessageSnapshotV1) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageSnapshotV1) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *MessageSnapshotV1) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_sem_timeline_message_proto protoreflect.FileDescriptor

const file_proto_sem_timeline_message_proto_rawDesc = "" +
	"\n" +
	" proto/sem/timeline/message.proto\x12\fsem.timeline\"\x8e\x02\n" +
	"\x11MessageSnapshotV1\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1c\n" +
	"\tstreaming\x18\x04 \x01(\bR\tstreaming\x12I\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2-.sem.timeline.MessageSnapshotV1.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BJZHgithub.com/go-go-golems/pinocchio/pkg/sem/pb/proto/sem/timeline;timelineb\x06proto3"

var (
	file_proto_sem_timeline_message_proto_rawDescOnce sync.Once
	file_proto_sem_timeline_message_proto_rawDescData []byte
)

func file_proto_sem_timeline_message_proto_rawDescGZIP() []byte {
	file_proto_sem_timeline_message_proto_rawDescOnce.Do(func() {
		file_proto_sem_timeline_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sem_timeline_message_proto_rawDesc), len(file_proto_sem_timeline_message_proto_rawDesc)))
	})
	return file_proto_sem_timeline_message_proto_rawDescData
}

var file_proto_sem_timeline_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sem_timeline_message_proto_goTypes = []any{
	(*MessageSnapshotV1)(nil), // 0: sem.timeline.MessageSnapshotV1
	nil,                       // 1: sem.timeline.MessageSnapshotV1.MetadataEntry
}
var file_proto_sem_timeline_message_proto_depIdxs = []int32{
	1, // 0: sem.timeline.MessageSnapshotV1.metadata:type_name -> sem.timeline.MessageSnapshotV1.MetadataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_sem_timeline_message_proto_init() }
func file_proto_sem_timeline_message_proto_init() {
	if File_proto_sem_timeline_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sem_timeline_message_proto_rawDesc), len(file_proto_sem_timeline_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sem_timeline_message_proto_goTypes,
		DependencyIndexes: file_proto_sem_timeline_message_proto_depIdxs,
		MessageInfos:      file_proto_sem_timeline_message_proto_msgTypes,
	}.Build()
	File_proto_sem_timeline_message_proto = out.File
	file_proto_sem_timeline_message_proto_goTypes = nil
	file_proto_sem_timeline_message_proto_depIdxs = nil
}
