// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/sem/timeline/middleware.proto

package timeline

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ThinkingModeSnapshotV1 maps 'thinking_mode' entity props
type ThinkingModeSnapshotV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // =1
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                     // active|completed|error
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Phase         string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	Reasoning     string                 `protobuf:"bytes,5,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	Success       bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkingModeSnapshotV1) Reset() {
	*x = ThinkingModeSnapshotV1{}
	mi := &file_proto_sem_timeline_middleware_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkingModeSnapshotV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkingModeSnapshotV1) ProtoMessage() {}

func (x *ThinkingModeSnapshotV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_timeline_middleware_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkingModeSnapshotV1.ProtoReflect.Descriptor instead.
func (*ThinkingModeSnapshotV1) Descriptor() ([]byte, []int) {
	return file_proto_sem_timeline_middleware_proto_rawDescGZIP(), []int{0}
}

func (x *ThinkingModeSnapshotV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ThinkingModeSnapshotV1) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ThinkingModeSnapshotV1) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ThinkingModeSnapshotV1) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ThinkingModeSnapshotV1) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *ThinkingModeSnapshotV1) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ThinkingModeSnapshotV1) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ModeEvaluationSnapshotV1 maps 'mode_evaluation' entity props
type ModeEvaluationSnapshotV1 struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion   uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // =1
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                     // active|completed|error
	CurrentMode     string                 `protobuf:"bytes,3,opt,name=current_mode,json=currentMode,proto3" json:"current_mode,omitempty"`
	Analysis        string                 `protobuf:"bytes,4,opt,name=analysis,proto3" json:"analysis,omitempty"`
	Decision        string                 `protobuf:"bytes,5,opt,name=decision,proto3" json:"decision,omitempty"`
	RecommendedMode string                 `protobuf:"bytes,6,opt,name=recommended_mode,json=recommendedMode,proto3" json:"recommended_mode,omitempty"`
	Success         bool                   `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`
	Error           string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ModeEvaluationSnapshotV1) Reset() {
	*x = ModeEvaluationSnapshotV1{}
	mi := &file_proto_sem_timeline_middleware_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeEvaluationSnapshotV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeEvaluationSnapshotV1) ProtoMessage() {}

func (x *ModeEvaluationSnapshotV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_timeline_middleware_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeEvaluationSnapshotV1.ProtoReflect.Descriptor instead.
func (*ModeEvaluationSnapshotV1) Descriptor() ([]byte, []int) {
	return file_proto_sem_timeline_middleware_proto_rawDescGZIP(), []int{1}
}

func (x *ModeEvaluationSnapshotV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ModeEvaluationSnapshotV1) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ModeEvaluationSnapshotV1) GetCurrentMode() string {
	if x != nil {
		return x.CurrentMode
	}
	return ""
}

func (x *ModeEvaluationSnapshotV1) GetAnalysis() string {
	if x != nil {
		return x.Analysis
	}
	return ""
}

func (x *ModeEvaluationSnapshotV1) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ModeEvaluationSnapshotV1) GetRecommendedMode() string {
	if x != nil {
		return x.RecommendedMode
	}
	return ""
}

func (x *ModeEvaluationSnapshotV1) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ModeEvaluationSnapshotV1) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// InnerThoughtsSnapshotV1 maps 'inner_thoughts' entity props
type InnerThoughtsSnapshotV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // =1
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                     // active|completed|error
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerThoughtsSnapshotV1) Reset() {
	*x = InnerThoughtsSnapshotV1{}
	mi := &file_proto_sem_timeline_middleware_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerThoughtsSnapshotV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerThoughtsSnapshotV1) ProtoMessage() {}

func (x *InnerThoughtsSnapshotV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_timeline_middleware_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerThoughtsSnapshotV1.ProtoReflect.Descriptor instead.
func (*InnerThoughtsSnapshotV1) Descriptor() ([]byte, []int) {
	return file_proto_sem_timeline_middleware_proto_rawDescGZIP(), []int{2}
}

func (x *InnerThoughtsSnapshotV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *InnerThoughtsSnapshotV1) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InnerThoughtsSnapshotV1) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_proto_sem_timeline_middleware_proto protoreflect.FileDescriptor

const file_proto_sem_timeline_middleware_proto_rawDesc = "" +
	"\n" +
	"#proto/sem/timeline/middleware.proto\x12\fsem.timeline\"\xcf\x01\n" +
	"\x16ThinkingModeSnapshotV1\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12\x1c\n" +
	"\treasoning\x18\x05 \x01(\tR\treasoning\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"\x8f\x02\n" +
	"\x18ModeEvaluationSnapshotV1\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_mode\x18\x03 \x01(\tR\vcurrentMode\x12\x1a\n" +
	"\banalysis\x18\x04 \x01(\tR\banalysis\x12\x1a\n" +
	"\bdecision\x18\x05 \x01(\tR\bdecision\x12)\n" +
	"\x10recommended_mode\x18\x06 \x01(\tR\x0frecommendedMode\x12\x18\n" +
	"\asuccess\x18\a \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"l\n" +
	"\x17InnerThoughtsSnapshotV1\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04textBJZHgithub.com/go-go-golems/pinocchio/pkg/sem/pb/proto/sem/timeline;timelineb\x06proto3"

var (
	file_proto_sem_timeline_middleware_proto_rawDescOnce sync.Once
	file_proto_sem_timeline_middleware_proto_rawDescData []byte
)

func file_proto_sem_timeline_middleware_proto_rawDescGZIP() []byte {
	file_proto_sem_timeline_middleware_proto_rawDescOnce.Do(func() {
		file_proto_sem_timeline_middleware_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sem_timeline_middleware_proto_rawDesc), len(file_proto_sem_timeline_middleware_proto_rawDesc)))
	})
	return file_proto_sem_timeline_middleware_proto_rawDescData
}

var file_proto_sem_timeline_middleware_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_sem_timeline_middleware_proto_goTypes = []any{
	(*ThinkingModeSnapshotV1)(nil),   // 0: sem.timeline.ThinkingModeSnapshotV1
	(*ModeEvaluationSnapshotV1)(nil), // 1: sem.timeline.ModeEvaluationSnapshotV1
	(*InnerThoughtsSnapshotV1)(nil),  // 2: sem.timeline.InnerThoughtsSnapshotV1
}
var file_proto_sem_timeline_middleware_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sem_timeline_middleware_proto_init() }
func file_proto_sem_timeline_middleware_proto_init() {
	if File_proto_sem_timeline_middleware_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sem_timeline_middleware_proto_rawDesc), len(file_proto_sem_timeline_middleware_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sem_timeline_middleware_proto_goTypes,
		DependencyIndexes: file_proto_sem_timeline_middleware_proto_depIdxs,
		MessageInfos:      file_proto_sem_timeline_middleware_proto_msgTypes,
	}.Build()
	File_proto_sem_timeline_middleware_proto = out.File
	file_proto_sem_timeline_middleware_proto_goTypes = nil
	file_proto_sem_timeline_middleware_proto_depIdxs = nil
}
