// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/sem/timeline/planning.proto

package timeline

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlanningIterationSnapshotV1 struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IterationIndex  int32                  `protobuf:"varint,1,opt,name=iteration_index,json=iterationIndex,proto3" json:"iteration_index,omitempty"` // 1-based
	Action          string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Reasoning       string                 `protobuf:"bytes,3,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	Strategy        string                 `protobuf:"bytes,4,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Progress        string                 `protobuf:"bytes,5,opt,name=progress,proto3" json:"progress,omitempty"`
	ToolName        string                 `protobuf:"bytes,6,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Extra           *structpb.Struct       `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"`
	EmittedAtUnixMs int64                  `protobuf:"varint,8,opt,name=emitted_at_unix_ms,json=emittedAtUnixMs,proto3" json:"emitted_at_unix_ms,omitempty"`
	ReflectionText  string                 `protobuf:"bytes,9,opt,name=reflection_text,json=reflectionText,proto3" json:"reflection_text,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlanningIterationSnapshotV1) Reset() {
	*x = PlanningIterationSnapshotV1{}
	mi := &file_proto_sem_timeline_planning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanningIterationSnapshotV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanningIterationSnapshotV1) ProtoMessage() {}

func (x *PlanningIterationSnapshotV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_timeline_planning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanningIterationSnapshotV1.ProtoReflect.Descriptor instead.
func (*PlanningIterationSnapshotV1) Descriptor() ([]byte, []int) {
	return file_proto_sem_timeline_planning_proto_rawDescGZIP(), []int{0}
}

func (x *PlanningIterationSnapshotV1) GetIterationIndex() int32 {
	if x != nil {
		return x.IterationIndex
	}
	return 0
}

func (x *PlanningIterationSnapshotV1) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PlanningIterationSnapshotV1) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *PlanningIterationSnapshotV1) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *PlanningIterationSnapshotV1) GetProgress() string {
	if x != nil {
		return x.Progress
	}
	return ""
}

func (x *PlanningIterationSnapshotV1) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *PlanningIterationSnapshotV1) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *PlanningIterationSnapshotV1) GetEmittedAtUnixMs() int64 {
	if x != nil {
		return x.EmittedAtUnixMs
	}
	return 0
}

func (x *PlanningIterationSnapshotV1) GetReflectionText() string {
	if x != nil {
		return x.ReflectionText
	}
	return ""
}

type ExecutionSnapshotV1 struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExecutorModel     string                 `protobuf:"bytes,1,opt,name=executor_model,json=executorModel,proto3" json:"executor_model,omitempty"`
	Directive         string                 `protobuf:"bytes,2,opt,name=directive,proto3" json:"directive,omitempty"`
	StartedAtUnixMs   int64                  `protobuf:"varint,3,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	CompletedAtUnixMs int64                  `protobuf:"varint,4,opt,name=completed_at_unix_ms,json=completedAtUnixMs,proto3" json:"completed_at_unix_ms,omitempty"`
	Status            string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                 // running|completed|error
	ErrorMessage      string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // optional
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecutionSnapshotV1) Reset() {
	*x = ExecutionSnapshotV1{}
	mi := &file_proto_sem_timeline_planning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionSnapshotV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionSnapshotV1) ProtoMessage() {}

func (x *ExecutionSnapshotV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_timeline_planning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionSnapshotV1.ProtoReflect.Descriptor instead.
func (*ExecutionSnapshotV1) Descriptor() ([]byte, []int) {
	return file_proto_sem_timeline_planning_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionSnapshotV1) GetExecutorModel() string {
	if x != nil {
		return x.ExecutorModel
	}
	return ""
}

func (x *ExecutionSnapshotV1) GetDirective() string {
	if x != nil {
		return x.Directive
	}
	return ""
}

func (x *ExecutionSnapshotV1) GetStartedAtUnixMs() int64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

func (x *ExecutionSnapshotV1) GetCompletedAtUnixMs() int64 {
	if x != nil {
		return x.CompletedAtUnixMs
	}
	return 0
}

func (x *ExecutionSnapshotV1) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutionSnapshotV1) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// PlanningSnapshotV1 defines the payload for a timeline 'planning' entity.
type PlanningSnapshotV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // =1
	// A single planner run (correlates to sem.middleware.planning.PlanningRun.run_id).
	RunId             string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Provider          string `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	PlannerModel      string `protobuf:"bytes,4,opt,name=planner_model,json=plannerModel,proto3" json:"planner_model,omitempty"`
	MaxIterations     int32  `protobuf:"varint,5,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	StartedAtUnixMs   int64  `protobuf:"varint,10,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	CompletedAtUnixMs int64  `protobuf:"varint,11,opt,name=completed_at_unix_ms,json=completedAtUnixMs,proto3" json:"completed_at_unix_ms,omitempty"`
	// planning|executing|completed|error
	Status         string                         `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	FinalDecision  string                         `protobuf:"bytes,13,opt,name=final_decision,json=finalDecision,proto3" json:"final_decision,omitempty"`
	StatusReason   string                         `protobuf:"bytes,14,opt,name=status_reason,json=statusReason,proto3" json:"status_reason,omitempty"`
	FinalDirective string                         `protobuf:"bytes,15,opt,name=final_directive,json=finalDirective,proto3" json:"final_directive,omitempty"`
	Iterations     []*PlanningIterationSnapshotV1 `protobuf:"bytes,20,rep,name=iterations,proto3" json:"iterations,omitempty"`
	Execution      *ExecutionSnapshotV1           `protobuf:"bytes,21,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlanningSnapshotV1) Reset() {
	*x = PlanningSnapshotV1{}
	mi := &file_proto_sem_timeline_planning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanningSnapshotV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanningSnapshotV1) ProtoMessage() {}

func (x *PlanningSnapshotV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_timeline_planning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanningSnapshotV1.ProtoReflect.Descriptor instead.
func (*PlanningSnapshotV1) Descriptor() ([]byte, []int) {
	return file_proto_sem_timeline_planning_proto_rawDescGZIP(), []int{2}
}

func (x *PlanningSnapshotV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *PlanningSnapshotV1) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *PlanningSnapshotV1) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PlanningSnapshotV1) GetPlannerModel() string {
	if x != nil {
		return x.PlannerModel
	}
	return ""
}

func (x *PlanningSnapshotV1) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *PlanningSnapshotV1) GetStartedAtUnixMs() int64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

func (x *PlanningSnapshotV1) GetCompletedAtUnixMs() int64 {
	if x != nil {
		return x.CompletedAtUnixMs
	}
	return 0
}

func (x *PlanningSnapshotV1) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PlanningSnapshotV1) GetFinalDecision() string {
	if x != nil {
		return x.FinalDecision
	}
	return ""
}

func (x *PlanningSnapshotV1) GetStatusReason() string {
	if x != nil {
		return x.StatusReason
	}
	return ""
}

func (x *PlanningSnapshotV1) GetFinalDirective() string {
	if x != nil {
		return x.FinalDirective
	}
	return ""
}

func (x *PlanningSnapshotV1) GetIterations() []*PlanningIterationSnapshotV1 {
	if x != nil {
		return x.Iterations
	}
	return nil
}

func (x *PlanningSnapshotV1) GetExecution() *ExecutionSnapshotV1 {
	if x != nil {
		return x.Execution
	}
	return nil
}

var File_proto_sem_timeline_planning_proto protoreflect.FileDescriptor

const file_proto_sem_timeline_planning_proto_rawDesc = "" +
	"\n" +
	"!proto/sem/timeline/planning.proto\x12\fsem.timeline\x1a\x1cgoogle/protobuf/struct.proto\"\xd6\x02\n" +
	"\x1bPlanningIterationSnapshotV1\x12'\n" +
	"\x0fiteration_index\x18\x01 \x01(\x05R\x0eiterationIndex\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1c\n" +
	"\treasoning\x18\x03 \x01(\tR\treasoning\x12\x1a\n" +
	"\bstrategy\x18\x04 \x01(\tR\bstrategy\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\tR\bprogress\x12\x1b\n" +
	"\ttool_name\x18\x06 \x01(\tR\btoolName\x12-\n" +
	"\x05extra\x18\a \x01(\v2\x17.google.protobuf.StructR\x05extra\x12+\n" +
	"\x12emitted_at_unix_ms\x18\b \x01(\x03R\x0femittedAtUnixMs\x12'\n" +
	"\x0freflection_text\x18\t \x01(\tR\x0ereflectionText\"\xf5\x01\n" +
	"\x13ExecutionSnapshotV1\x12%\n" +
	"\x0eexecutor_model\x18\x01 \x01(\tR\rexecutorModel\x12\x1c\n" +
	"\tdirective\x18\x02 \x01(\tR\tdirective\x12+\n" +
	"\x12started_at_unix_ms\x18\x03 \x01(\x03R\x0fstartedAtUnixMs\x12/\n" +
	"\x14completed_at_unix_ms\x18\x04 \x01(\x03R\x11completedAtUnixMs\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\xb1\x04\n" +
	"\x12PlanningSnapshotV1\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12#\n" +
	"\rplanner_model\x18\x04 \x01(\tR\fplannerModel\x12%\n" +
	"\x0emax_iterations\x18\x05 \x01(\x05R\rmaxIterations\x12+\n" +
	"\x12started_at_unix_ms\x18\n" +
	" \x01(\x03R\x0fstartedAtUnixMs\x12/\n" +
	"\x14completed_at_unix_ms\x18\v \x01(\x03R\x11completedAtUnixMs\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12%\n" +
	"\x0efinal_decision\x18\r \x01(\tR\rfinalDecision\x12#\n" +
	"\rstatus_reason\x18\x0e \x01(\tR\fstatusReason\x12'\n" +
	"\x0ffinal_directive\x18\x0f \x01(\tR\x0efinalDirective\x12I\n" +
	"\n" +
	"iterations\x18\x14 \x03(\v2).sem.timeline.PlanningIterationSnapshotV1R\n" +
	"iterations\x12?\n" +
	"\texecution\x18\x15 \x01(\v2!.sem.timeline.ExecutionSnapshotV1R\texecutionBJZHgithub.com/go-go-golems/pinocchio/pkg/sem/pb/proto/sem/timeline;timelineb\x06proto3"

var (
	file_proto_sem_timeline_planning_proto_rawDescOnce sync.Once
	file_proto_sem_timeline_planning_proto_rawDescData []byte
)

func file_proto_sem_timeline_planning_proto_rawDescGZIP() []byte {
	file_proto_sem_timeline_planning_proto_rawDescOnce.Do(func() {
		file_proto_sem_timeline_planning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sem_timeline_planning_proto_rawDesc), len(file_proto_sem_timeline_planning_proto_rawDesc)))
	})
	return file_proto_sem_timeline_planning_proto_rawDescData
}

var file_proto_sem_timeline_planning_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_sem_timeline_planning_proto_goTypes = []any{
	(*PlanningIterationSnapshotV1)(nil), // 0: sem.timeline.PlanningIterationSnapshotV1
	(*ExecutionSnapshotV1)(nil),         // 1: sem.timeline.ExecutionSnapshotV1
	(*PlanningSnapshotV1)(nil),          // 2: sem.timeline.PlanningSnapshotV1
	(*structpb.Struct)(nil),             // 3: google.protobuf.Struct
}
var file_proto_sem_timeline_planning_proto_depIdxs = []int32{
	3, // 0: sem.timeline.PlanningIterationSnapshotV1.extra:type_name -> google.protobuf.Struct
	0, // 1: sem.timeline.PlanningSnapshotV1.iterations:type_name -> sem.timeline.PlanningIterationSnapshotV1
	1, // 2: sem.timeline.PlanningSnapshotV1.execution:type_name -> sem.timeline.ExecutionSnapshotV1
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_sem_timeline_planning_proto_init() }
func file_proto_sem_timeline_planning_proto_init() {
	if File_proto_sem_timeline_planning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sem_timeline_planning_proto_rawDesc), len(file_proto_sem_timeline_planning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sem_timeline_planning_proto_goTypes,
		DependencyIndexes: file_proto_sem_timeline_planning_proto_depIdxs,
		MessageInfos:      file_proto_sem_timeline_planning_proto_msgTypes,
	}.Build()
	File_proto_sem_timeline_planning_proto = out.File
	file_proto_sem_timeline_planning_proto_goTypes = nil
	file_proto_sem_timeline_planning_proto_depIdxs = nil
}
