// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/sem/timeline/tool.proto

package timeline

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ToolCallSnapshotV1 defines the payload for a 'tool_call' entity.
type ToolCallSnapshotV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // =1
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Input         *structpb.Struct       `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`         // structured input
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`       // queued|running|completed|error
	Progress      float64                `protobuf:"fixed64,5,opt,name=progress,proto3" json:"progress,omitempty"` // 0..1
	Done          bool                   `protobuf:"varint,6,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallSnapshotV1) Reset() {
	*x = ToolCallSnapshotV1{}
	mi := &file_proto_sem_timeline_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallSnapshotV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallSnapshotV1) ProtoMessage() {}

func (x *ToolCallSnapshotV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_timeline_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallSnapshotV1.ProtoReflect.Descriptor instead.
func (*ToolCallSnapshotV1) Descriptor() ([]byte, []int) {
	return file_proto_sem_timeline_tool_proto_rawDescGZIP(), []int{0}
}

func (x *ToolCallSnapshotV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ToolCallSnapshotV1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCallSnapshotV1) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ToolCallSnapshotV1) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ToolCallSnapshotV1) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ToolCallSnapshotV1) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

// ToolResultSnapshotV1 defines the payload for a 'tool_result' entity.
type ToolResultSnapshotV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // =1
	ToolCallId    string                 `protobuf:"bytes,2,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`         // -> toolCallId (camelCase) in JSON
	Result        *structpb.Struct       `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`                                     // structured result
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                                       // optional
	// Optional: raw result text when the tool result is not structured JSON.
	ResultRaw string `protobuf:"bytes,5,opt,name=result_raw,json=resultRaw,proto3" json:"result_raw,omitempty"`
	// Optional: renderer hint (e.g. "calc_result") carried through from SEM tool.result.
	CustomKind    string `protobuf:"bytes,6,opt,name=custom_kind,json=customKind,proto3" json:"custom_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResultSnapshotV1) Reset() {
	*x = ToolResultSnapshotV1{}
	mi := &file_proto_sem_timeline_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultSnapshotV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultSnapshotV1) ProtoMessage() {}

func (x *ToolResultSnapshotV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_timeline_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResultSnapshotV1.ProtoReflect.Descriptor instead.
func (*ToolResultSnapshotV1) Descriptor() ([]byte, []int) {
	return file_proto_sem_timeline_tool_proto_rawDescGZIP(), []int{1}
}

func (x *ToolResultSnapshotV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ToolResultSnapshotV1) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolResultSnapshotV1) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ToolResultSnapshotV1) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ToolResultSnapshotV1) GetResultRaw() string {
	if x != nil {
		return x.ResultRaw
	}
	return ""
}

func (x *ToolResultSnapshotV1) GetCustomKind() string {
	if x != nil {
		return x.CustomKind
	}
	return ""
}

var File_proto_sem_timeline_tool_proto protoreflect.FileDescriptor

const file_proto_sem_timeline_tool_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/sem/timeline/tool.proto\x12\fsem.timeline\x1a\x1cgoogle/protobuf/struct.proto\"\xc6\x01\n" +
	"\x12ToolCallSnapshotV1\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x05input\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05input\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x01R\bprogress\x12\x12\n" +
	"\x04done\x18\x06 \x01(\bR\x04done\"\xe6\x01\n" +
	"\x14ToolResultSnapshotV1\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12 \n" +
	"\ftool_call_id\x18\x02 \x01(\tR\n" +
	"toolCallId\x12/\n" +
	"\x06result\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"result_raw\x18\x05 \x01(\tR\tresultRaw\x12\x1f\n" +
	"\vcustom_kind\x18\x06 \x01(\tR\n" +
	"customKindBJZHgithub.com/go-go-golems/pinocchio/pkg/sem/pb/proto/sem/timeline;timelineb\x06proto3"

var (
	file_proto_sem_timeline_tool_proto_rawDescOnce sync.Once
	file_proto_sem_timeline_tool_proto_rawDescData []byte
)

func file_proto_sem_timeline_tool_proto_rawDescGZIP() []byte {
	file_proto_sem_timeline_tool_proto_rawDescOnce.Do(func() {
		file_proto_sem_timeline_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sem_timeline_tool_proto_rawDesc), len(file_proto_sem_timeline_tool_proto_rawDesc)))
	})
	return file_proto_sem_timeline_tool_proto_rawDescData
}

var file_proto_sem_timeline_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sem_timeline_tool_proto_goTypes = []any{
	(*ToolCallSnapshotV1)(nil),   // 0: sem.timeline.ToolCallSnapshotV1
	(*ToolResultSnapshotV1)(nil), // 1: sem.timeline.ToolResultSnapshotV1
	(*structpb.Struct)(nil),      // 2: google.protobuf.Struct
}
var file_proto_sem_timeline_tool_proto_depIdxs = []int32{
	2, // 0: sem.timeline.ToolCallSnapshotV1.input:type_name -> google.protobuf.Struct
	2, // 1: sem.timeline.ToolResultSnapshotV1.result:type_name -> google.protobuf.Struct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_sem_timeline_tool_proto_init() }
func file_proto_sem_timeline_tool_proto_init() {
	if File_proto_sem_timeline_tool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sem_timeline_tool_proto_rawDesc), len(file_proto_sem_timeline_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sem_timeline_tool_proto_goTypes,
		DependencyIndexes: file_proto_sem_timeline_tool_proto_depIdxs,
		MessageInfos:      file_proto_sem_timeline_tool_proto_msgTypes,
	}.Build()
	File_proto_sem_timeline_tool_proto = out.File
	file_proto_sem_timeline_tool_proto_goTypes = nil
	file_proto_sem_timeline_tool_proto_depIdxs = nil
}
