// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/sem/middleware/next_thinking_mode.proto

package middleware

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NextThinkingModePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Reasoning     string                 `protobuf:"bytes,2,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	Confidence    string                 `protobuf:"bytes,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextThinkingModePayload) Reset() {
	*x = NextThinkingModePayload{}
	mi := &file_proto_sem_middleware_next_thinking_mode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextThinkingModePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextThinkingModePayload) ProtoMessage() {}

func (x *NextThinkingModePayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_middleware_next_thinking_mode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextThinkingModePayload.ProtoReflect.Descriptor instead.
func (*NextThinkingModePayload) Descriptor() ([]byte, []int) {
	return file_proto_sem_middleware_next_thinking_mode_proto_rawDescGZIP(), []int{0}
}

func (x *NextThinkingModePayload) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *NextThinkingModePayload) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *NextThinkingModePayload) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

type NextThinkingModeStarted struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	ItemId        string                   `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Data          *NextThinkingModePayload `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextThinkingModeStarted) Reset() {
	*x = NextThinkingModeStarted{}
	mi := &file_proto_sem_middleware_next_thinking_mode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextThinkingModeStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextThinkingModeStarted) ProtoMessage() {}

func (x *NextThinkingModeStarted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_middleware_next_thinking_mode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextThinkingModeStarted.ProtoReflect.Descriptor instead.
func (*NextThinkingModeStarted) Descriptor() ([]byte, []int) {
	return file_proto_sem_middleware_next_thinking_mode_proto_rawDescGZIP(), []int{1}
}

func (x *NextThinkingModeStarted) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *NextThinkingModeStarted) GetData() *NextThinkingModePayload {
	if x != nil {
		return x.Data
	}
	return nil
}

type NextThinkingModeUpdate struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	ItemId        string                   `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Data          *NextThinkingModePayload `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextThinkingModeUpdate) Reset() {
	*x = NextThinkingModeUpdate{}
	mi := &file_proto_sem_middleware_next_thinking_mode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextThinkingModeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextThinkingModeUpdate) ProtoMessage() {}

func (x *NextThinkingModeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_middleware_next_thinking_mode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextThinkingModeUpdate.ProtoReflect.Descriptor instead.
func (*NextThinkingModeUpdate) Descriptor() ([]byte, []int) {
	return file_proto_sem_middleware_next_thinking_mode_proto_rawDescGZIP(), []int{2}
}

func (x *NextThinkingModeUpdate) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *NextThinkingModeUpdate) GetData() *NextThinkingModePayload {
	if x != nil {
		return x.Data
	}
	return nil
}

type NextThinkingModeCompleted struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	ItemId        string                   `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Data          *NextThinkingModePayload `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Success       bool                     `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextThinkingModeCompleted) Reset() {
	*x = NextThinkingModeCompleted{}
	mi := &file_proto_sem_middleware_next_thinking_mode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextThinkingModeCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextThinkingModeCompleted) ProtoMessage() {}

func (x *NextThinkingModeCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_middleware_next_thinking_mode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextThinkingModeCompleted.ProtoReflect.Descriptor instead.
func (*NextThinkingModeCompleted) Descriptor() ([]byte, []int) {
	return file_proto_sem_middleware_next_thinking_mode_proto_rawDescGZIP(), []int{3}
}

func (x *NextThinkingModeCompleted) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *NextThinkingModeCompleted) GetData() *NextThinkingModePayload {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *NextThinkingModeCompleted) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NextThinkingModeCompleted) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_sem_middleware_next_thinking_mode_proto protoreflect.FileDescriptor

const file_proto_sem_middleware_next_thinking_mode_proto_rawDesc = "" +
	"\n" +
	"-proto/sem/middleware/next_thinking_mode.proto\x12!sem.middleware.next_thinking_mode\"k\n" +
	"\x17NextThinkingModePayload\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x1c\n" +
	"\treasoning\x18\x02 \x01(\tR\treasoning\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\tR\n" +
	"confidence\"\x82\x01\n" +
	"\x17NextThinkingModeStarted\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12N\n" +
	"\x04data\x18\x02 \x01(\v2:.sem.middleware.next_thinking_mode.NextThinkingModePayloadR\x04data\"\x81\x01\n" +
	"\x16NextThinkingModeUpdate\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12N\n" +
	"\x04data\x18\x02 \x01(\v2:.sem.middleware.next_thinking_mode.NextThinkingModePayloadR\x04data\"\xb4\x01\n" +
	"\x19NextThinkingModeCompleted\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12N\n" +
	"\x04data\x18\x02 \x01(\v2:.sem.middleware.next_thinking_mode.NextThinkingModePayloadR\x04data\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05errorBNZLgithub.com/go-go-golems/pinocchio/pkg/sem/pb/proto/sem/middleware;middlewareb\x06proto3"

var (
	file_proto_sem_middleware_next_thinking_mode_proto_rawDescOnce sync.Once
	file_proto_sem_middleware_next_thinking_mode_proto_rawDescData []byte
)

func file_proto_sem_middleware_next_thinking_mode_proto_rawDescGZIP() []byte {
	file_proto_sem_middleware_next_thinking_mode_proto_rawDescOnce.Do(func() {
		file_proto_sem_middleware_next_thinking_mode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sem_middleware_next_thinking_mode_proto_rawDesc), len(file_proto_sem_middleware_next_thinking_mode_proto_rawDesc)))
	})
	return file_proto_sem_middleware_next_thinking_mode_proto_rawDescData
}

var file_proto_sem_middleware_next_thinking_mode_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_sem_middleware_next_thinking_mode_proto_goTypes = []any{
	(*NextThinkingModePayload)(nil),   // 0: sem.middleware.next_thinking_mode.NextThinkingModePayload
	(*NextThinkingModeStarted)(nil),   // 1: sem.middleware.next_thinking_mode.NextThinkingModeStarted
	(*NextThinkingModeUpdate)(nil),    // 2: sem.middleware.next_thinking_mode.NextThinkingModeUpdate
	(*NextThinkingModeCompleted)(nil), // 3: sem.middleware.next_thinking_mode.NextThinkingModeCompleted
}
var file_proto_sem_middleware_next_thinking_mode_proto_depIdxs = []int32{
	0, // 0: sem.middleware.next_thinking_mode.NextThinkingModeStarted.data:type_name -> sem.middleware.next_thinking_mode.NextThinkingModePayload
	0, // 1: sem.middleware.next_thinking_mode.NextThinkingModeUpdate.data:type_name -> sem.middleware.next_thinking_mode.NextThinkingModePayload
	0, // 2: sem.middleware.next_thinking_mode.NextThinkingModeCompleted.data:type_name -> sem.middleware.next_thinking_mode.NextThinkingModePayload
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_sem_middleware_next_thinking_mode_proto_init() }
func file_proto_sem_middleware_next_thinking_mode_proto_init() {
	if File_proto_sem_middleware_next_thinking_mode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sem_middleware_next_thinking_mode_proto_rawDesc), len(file_proto_sem_middleware_next_thinking_mode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sem_middleware_next_thinking_mode_proto_goTypes,
		DependencyIndexes: file_proto_sem_middleware_next_thinking_mode_proto_depIdxs,
		MessageInfos:      file_proto_sem_middleware_next_thinking_mode_proto_msgTypes,
	}.Build()
	File_proto_sem_middleware_next_thinking_mode_proto = out.File
	file_proto_sem_middleware_next_thinking_mode_proto_goTypes = nil
	file_proto_sem_middleware_next_thinking_mode_proto_depIdxs = nil
}
