// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/sem/middleware/planning.proto

package middleware

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Shared identifier for a single planner run.
type PlanningRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	PlannerModel  string                 `protobuf:"bytes,3,opt,name=planner_model,json=plannerModel,proto3" json:"planner_model,omitempty"`
	MaxIterations int32                  `protobuf:"varint,4,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanningRun) Reset() {
	*x = PlanningRun{}
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanningRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanningRun) ProtoMessage() {}

func (x *PlanningRun) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanningRun.ProtoReflect.Descriptor instead.
func (*PlanningRun) Descriptor() ([]byte, []int) {
	return file_proto_sem_middleware_planning_proto_rawDescGZIP(), []int{0}
}

func (x *PlanningRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *PlanningRun) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PlanningRun) GetPlannerModel() string {
	if x != nil {
		return x.PlannerModel
	}
	return ""
}

func (x *PlanningRun) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

// Fired once per run when planning begins.
type PlanningStarted struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Run             *PlanningRun           `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	StartedAtUnixMs int64                  `protobuf:"varint,2,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlanningStarted) Reset() {
	*x = PlanningStarted{}
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanningStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanningStarted) ProtoMessage() {}

func (x *PlanningStarted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanningStarted.ProtoReflect.Descriptor instead.
func (*PlanningStarted) Descriptor() ([]byte, []int) {
	return file_proto_sem_middleware_planning_proto_rawDescGZIP(), []int{1}
}

func (x *PlanningStarted) GetRun() *PlanningRun {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *PlanningStarted) GetStartedAtUnixMs() int64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

// Fired for each iteration the planner produces.
type PlanningIteration struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Run             *PlanningRun           `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	IterationIndex  int32                  `protobuf:"varint,2,opt,name=iteration_index,json=iterationIndex,proto3" json:"iteration_index,omitempty"`
	Action          string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Reasoning       string                 `protobuf:"bytes,4,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	Strategy        string                 `protobuf:"bytes,5,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Progress        string                 `protobuf:"bytes,6,opt,name=progress,proto3" json:"progress,omitempty"`
	ToolName        string                 `protobuf:"bytes,7,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Extra           *structpb.Struct       `protobuf:"bytes,8,opt,name=extra,proto3" json:"extra,omitempty"`
	EmittedAtUnixMs int64                  `protobuf:"varint,9,opt,name=emitted_at_unix_ms,json=emittedAtUnixMs,proto3" json:"emitted_at_unix_ms,omitempty"`
	ReflectionText  string                 `protobuf:"bytes,10,opt,name=reflection_text,json=reflectionText,proto3" json:"reflection_text,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlanningIteration) Reset() {
	*x = PlanningIteration{}
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanningIteration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanningIteration) ProtoMessage() {}

func (x *PlanningIteration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanningIteration.ProtoReflect.Descriptor instead.
func (*PlanningIteration) Descriptor() ([]byte, []int) {
	return file_proto_sem_middleware_planning_proto_rawDescGZIP(), []int{2}
}

func (x *PlanningIteration) GetRun() *PlanningRun {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *PlanningIteration) GetIterationIndex() int32 {
	if x != nil {
		return x.IterationIndex
	}
	return 0
}

func (x *PlanningIteration) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PlanningIteration) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *PlanningIteration) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *PlanningIteration) GetProgress() string {
	if x != nil {
		return x.Progress
	}
	return ""
}

func (x *PlanningIteration) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *PlanningIteration) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *PlanningIteration) GetEmittedAtUnixMs() int64 {
	if x != nil {
		return x.EmittedAtUnixMs
	}
	return 0
}

func (x *PlanningIteration) GetReflectionText() string {
	if x != nil {
		return x.ReflectionText
	}
	return ""
}

// Optional intermediate reflection snapshots keyed by iteration.
type PlanningReflection struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Run             *PlanningRun           `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	IterationIndex  int32                  `protobuf:"varint,2,opt,name=iteration_index,json=iterationIndex,proto3" json:"iteration_index,omitempty"`
	ReflectionText  string                 `protobuf:"bytes,3,opt,name=reflection_text,json=reflectionText,proto3" json:"reflection_text,omitempty"`
	ProgressScore   float64                `protobuf:"fixed64,4,opt,name=progress_score,json=progressScore,proto3" json:"progress_score,omitempty"`
	EmittedAtUnixMs int64                  `protobuf:"varint,5,opt,name=emitted_at_unix_ms,json=emittedAtUnixMs,proto3" json:"emitted_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlanningReflection) Reset() {
	*x = PlanningReflection{}
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanningReflection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanningReflection) ProtoMessage() {}

func (x *PlanningReflection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanningReflection.ProtoReflect.Descriptor instead.
func (*PlanningReflection) Descriptor() ([]byte, []int) {
	return file_proto_sem_middleware_planning_proto_rawDescGZIP(), []int{3}
}

func (x *PlanningReflection) GetRun() *PlanningRun {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *PlanningReflection) GetIterationIndex() int32 {
	if x != nil {
		return x.IterationIndex
	}
	return 0
}

func (x *PlanningReflection) GetReflectionText() string {
	if x != nil {
		return x.ReflectionText
	}
	return ""
}

func (x *PlanningReflection) GetProgressScore() float64 {
	if x != nil {
		return x.ProgressScore
	}
	return 0
}

func (x *PlanningReflection) GetEmittedAtUnixMs() int64 {
	if x != nil {
		return x.EmittedAtUnixMs
	}
	return 0
}

// Fired when planning concludes (even with zero iterations).
type PlanningCompleted struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Run               *PlanningRun           `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	TotalIterations   int32                  `protobuf:"varint,2,opt,name=total_iterations,json=totalIterations,proto3" json:"total_iterations,omitempty"`
	FinalDecision     string                 `protobuf:"bytes,3,opt,name=final_decision,json=finalDecision,proto3" json:"final_decision,omitempty"`
	StatusReason      string                 `protobuf:"bytes,4,opt,name=status_reason,json=statusReason,proto3" json:"status_reason,omitempty"`
	FinalDirective    string                 `protobuf:"bytes,5,opt,name=final_directive,json=finalDirective,proto3" json:"final_directive,omitempty"`
	CompletedAtUnixMs int64                  `protobuf:"varint,6,opt,name=completed_at_unix_ms,json=completedAtUnixMs,proto3" json:"completed_at_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlanningCompleted) Reset() {
	*x = PlanningCompleted{}
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanningCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanningCompleted) ProtoMessage() {}

func (x *PlanningCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanningCompleted.ProtoReflect.Descriptor instead.
func (*PlanningCompleted) Descriptor() ([]byte, []int) {
	return file_proto_sem_middleware_planning_proto_rawDescGZIP(), []int{4}
}

func (x *PlanningCompleted) GetRun() *PlanningRun {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *PlanningCompleted) GetTotalIterations() int32 {
	if x != nil {
		return x.TotalIterations
	}
	return 0
}

func (x *PlanningCompleted) GetFinalDecision() string {
	if x != nil {
		return x.FinalDecision
	}
	return ""
}

func (x *PlanningCompleted) GetStatusReason() string {
	if x != nil {
		return x.StatusReason
	}
	return ""
}

func (x *PlanningCompleted) GetFinalDirective() string {
	if x != nil {
		return x.FinalDirective
	}
	return ""
}

func (x *PlanningCompleted) GetCompletedAtUnixMs() int64 {
	if x != nil {
		return x.CompletedAtUnixMs
	}
	return 0
}

// Optional: token-level streaming of the planner's raw output (typically JSON).
// These events are meant for live UX only; they are usually not persisted into projections.
type PlanningTextStarted struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Run             *PlanningRun           `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	StartedAtUnixMs int64                  `protobuf:"varint,2,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlanningTextStarted) Reset() {
	*x = PlanningTextStarted{}
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanningTextStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanningTextStarted) ProtoMessage() {}

func (x *PlanningTextStarted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanningTextStarted.ProtoReflect.Descriptor instead.
func (*PlanningTextStarted) Descriptor() ([]byte, []int) {
	return file_proto_sem_middleware_planning_proto_rawDescGZIP(), []int{5}
}

func (x *PlanningTextStarted) GetRun() *PlanningRun {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *PlanningTextStarted) GetStartedAtUnixMs() int64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

type PlanningTextDelta struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Run             *PlanningRun           `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	Delta           string                 `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`
	Cumulative      string                 `protobuf:"bytes,3,opt,name=cumulative,proto3" json:"cumulative,omitempty"`
	EmittedAtUnixMs int64                  `protobuf:"varint,4,opt,name=emitted_at_unix_ms,json=emittedAtUnixMs,proto3" json:"emitted_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlanningTextDelta) Reset() {
	*x = PlanningTextDelta{}
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanningTextDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanningTextDelta) ProtoMessage() {}

func (x *PlanningTextDelta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanningTextDelta.ProtoReflect.Descriptor instead.
func (*PlanningTextDelta) Descriptor() ([]byte, []int) {
	return file_proto_sem_middleware_planning_proto_rawDescGZIP(), []int{6}
}

func (x *PlanningTextDelta) GetRun() *PlanningRun {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *PlanningTextDelta) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *PlanningTextDelta) GetCumulative() string {
	if x != nil {
		return x.Cumulative
	}
	return ""
}

func (x *PlanningTextDelta) GetEmittedAtUnixMs() int64 {
	if x != nil {
		return x.EmittedAtUnixMs
	}
	return 0
}

type PlanningTextFinal struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Run               *PlanningRun           `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	Text              string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	CompletedAtUnixMs int64                  `protobuf:"varint,3,opt,name=completed_at_unix_ms,json=completedAtUnixMs,proto3" json:"completed_at_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlanningTextFinal) Reset() {
	*x = PlanningTextFinal{}
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanningTextFinal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanningTextFinal) ProtoMessage() {}

func (x *PlanningTextFinal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanningTextFinal.ProtoReflect.Descriptor instead.
func (*PlanningTextFinal) Descriptor() ([]byte, []int) {
	return file_proto_sem_middleware_planning_proto_rawDescGZIP(), []int{7}
}

func (x *PlanningTextFinal) GetRun() *PlanningRun {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *PlanningTextFinal) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PlanningTextFinal) GetCompletedAtUnixMs() int64 {
	if x != nil {
		return x.CompletedAtUnixMs
	}
	return 0
}

// Execution starts once a final directive is available.
type ExecutionStarted struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RunId           string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ExecutorModel   string                 `protobuf:"bytes,2,opt,name=executor_model,json=executorModel,proto3" json:"executor_model,omitempty"`
	Directive       string                 `protobuf:"bytes,3,opt,name=directive,proto3" json:"directive,omitempty"`
	StartedAtUnixMs int64                  `protobuf:"varint,4,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecutionStarted) Reset() {
	*x = ExecutionStarted{}
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionStarted) ProtoMessage() {}

func (x *ExecutionStarted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionStarted.ProtoReflect.Descriptor instead.
func (*ExecutionStarted) Descriptor() ([]byte, []int) {
	return file_proto_sem_middleware_planning_proto_rawDescGZIP(), []int{8}
}

func (x *ExecutionStarted) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecutionStarted) GetExecutorModel() string {
	if x != nil {
		return x.ExecutorModel
	}
	return ""
}

func (x *ExecutionStarted) GetDirective() string {
	if x != nil {
		return x.Directive
	}
	return ""
}

func (x *ExecutionStarted) GetStartedAtUnixMs() int64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

// Completion of the execution phase; reserved for richer result payloads.
type ExecutionCompleted struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RunId             string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	CompletedAtUnixMs int64                  `protobuf:"varint,2,opt,name=completed_at_unix_ms,json=completedAtUnixMs,proto3" json:"completed_at_unix_ms,omitempty"`
	Status            string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TokensUsed        int32                  `protobuf:"varint,5,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	ResponseLength    int32                  `protobuf:"varint,6,opt,name=response_length,json=responseLength,proto3" json:"response_length,omitempty"`
	Extra             *structpb.Struct       `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecutionCompleted) Reset() {
	*x = ExecutionCompleted{}
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionCompleted) ProtoMessage() {}

func (x *ExecutionCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_middleware_planning_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionCompleted.ProtoReflect.Descriptor instead.
func (*ExecutionCompleted) Descriptor() ([]byte, []int) {
	return file_proto_sem_middleware_planning_proto_rawDescGZIP(), []int{9}
}

func (x *ExecutionCompleted) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecutionCompleted) GetCompletedAtUnixMs() int64 {
	if x != nil {
		return x.CompletedAtUnixMs
	}
	return 0
}

func (x *ExecutionCompleted) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutionCompleted) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExecutionCompleted) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *ExecutionCompleted) GetResponseLength() int32 {
	if x != nil {
		return x.ResponseLength
	}
	return 0
}

func (x *ExecutionCompleted) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

var File_proto_sem_middleware_planning_proto protoreflect.FileDescriptor

const file_proto_sem_middleware_planning_proto_rawDesc = "" +
	"\n" +
	"#proto/sem/middleware/planning.proto\x12\x17sem.middleware.planning\x1a\x1cgoogle/protobuf/struct.proto\"\x8c\x01\n" +
	"\vPlanningRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12#\n" +
	"\rplanner_model\x18\x03 \x01(\tR\fplannerModel\x12%\n" +
	"\x0emax_iterations\x18\x04 \x01(\x05R\rmaxIterations\"v\n" +
	"\x0fPlanningStarted\x126\n" +
	"\x03run\x18\x01 \x01(\v2$.sem.middleware.planning.PlanningRunR\x03run\x12+\n" +
	"\x12started_at_unix_ms\x18\x02 \x01(\x03R\x0fstartedAtUnixMs\"\x84\x03\n" +
	"\x11PlanningIteration\x126\n" +
	"\x03run\x18\x01 \x01(\v2$.sem.middleware.planning.PlanningRunR\x03run\x12'\n" +
	"\x0fiteration_index\x18\x02 \x01(\x05R\x0eiterationIndex\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1c\n" +
	"\treasoning\x18\x04 \x01(\tR\treasoning\x12\x1a\n" +
	"\bstrategy\x18\x05 \x01(\tR\bstrategy\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\tR\bprogress\x12\x1b\n" +
	"\ttool_name\x18\a \x01(\tR\btoolName\x12-\n" +
	"\x05extra\x18\b \x01(\v2\x17.google.protobuf.StructR\x05extra\x12+\n" +
	"\x12emitted_at_unix_ms\x18\t \x01(\x03R\x0femittedAtUnixMs\x12'\n" +
	"\x0freflection_text\x18\n" +
	" \x01(\tR\x0ereflectionText\"\xf2\x01\n" +
	"\x12PlanningReflection\x126\n" +
	"\x03run\x18\x01 \x01(\v2$.sem.middleware.planning.PlanningRunR\x03run\x12'\n" +
	"\x0fiteration_index\x18\x02 \x01(\x05R\x0eiterationIndex\x12'\n" +
	"\x0freflection_text\x18\x03 \x01(\tR\x0ereflectionText\x12%\n" +
	"\x0eprogress_score\x18\x04 \x01(\x01R\rprogressScore\x12+\n" +
	"\x12emitted_at_unix_ms\x18\x05 \x01(\x03R\x0femittedAtUnixMs\"\x9c\x02\n" +
	"\x11PlanningCompleted\x126\n" +
	"\x03run\x18\x01 \x01(\v2$.sem.middleware.planning.PlanningRunR\x03run\x12)\n" +
	"\x10total_iterations\x18\x02 \x01(\x05R\x0ftotalIterations\x12%\n" +
	"\x0efinal_decision\x18\x03 \x01(\tR\rfinalDecision\x12#\n" +
	"\rstatus_reason\x18\x04 \x01(\tR\fstatusReason\x12'\n" +
	"\x0ffinal_directive\x18\x05 \x01(\tR\x0efinalDirective\x12/\n" +
	"\x14completed_at_unix_ms\x18\x06 \x01(\x03R\x11completedAtUnixMs\"z\n" +
	"\x13PlanningTextStarted\x126\n" +
	"\x03run\x18\x01 \x01(\v2$.sem.middleware.planning.PlanningRunR\x03run\x12+\n" +
	"\x12started_at_unix_ms\x18\x02 \x01(\x03R\x0fstartedAtUnixMs\"\xae\x01\n" +
	"\x11PlanningTextDelta\x126\n" +
	"\x03run\x18\x01 \x01(\v2$.sem.middleware.planning.PlanningRunR\x03run\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\tR\x05delta\x12\x1e\n" +
	"\n" +
	"cumulative\x18\x03 \x01(\tR\n" +
	"cumulative\x12+\n" +
	"\x12emitted_at_unix_ms\x18\x04 \x01(\x03R\x0femittedAtUnixMs\"\x90\x01\n" +
	"\x11PlanningTextFinal\x126\n" +
	"\x03run\x18\x01 \x01(\v2$.sem.middleware.planning.PlanningRunR\x03run\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12/\n" +
	"\x14completed_at_unix_ms\x18\x03 \x01(\x03R\x11completedAtUnixMs\"\x9b\x01\n" +
	"\x10ExecutionStarted\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12%\n" +
	"\x0eexecutor_model\x18\x02 \x01(\tR\rexecutorModel\x12\x1c\n" +
	"\tdirective\x18\x03 \x01(\tR\tdirective\x12+\n" +
	"\x12started_at_unix_ms\x18\x04 \x01(\x03R\x0fstartedAtUnixMs\"\x92\x02\n" +
	"\x12ExecutionCompleted\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12/\n" +
	"\x14completed_at_unix_ms\x18\x02 \x01(\x03R\x11completedAtUnixMs\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vtokens_used\x18\x05 \x01(\x05R\n" +
	"tokensUsed\x12'\n" +
	"\x0fresponse_length\x18\x06 \x01(\x05R\x0eresponseLength\x12-\n" +
	"\x05extra\x18\a \x01(\v2\x17.google.protobuf.StructR\x05extraBNZLgithub.com/go-go-golems/pinocchio/pkg/sem/pb/proto/sem/middleware;middlewareb\x06proto3"

var (
	file_proto_sem_middleware_planning_proto_rawDescOnce sync.Once
	file_proto_sem_middleware_planning_proto_rawDescData []byte
)

func file_proto_sem_middleware_planning_proto_rawDescGZIP() []byte {
	file_proto_sem_middleware_planning_proto_rawDescOnce.Do(func() {
		file_proto_sem_middleware_planning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sem_middleware_planning_proto_rawDesc), len(file_proto_sem_middleware_planning_proto_rawDesc)))
	})
	return file_proto_sem_middleware_planning_proto_rawDescData
}

var file_proto_sem_middleware_planning_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_sem_middleware_planning_proto_goTypes = []any{
	(*PlanningRun)(nil),         // 0: sem.middleware.planning.PlanningRun
	(*PlanningStarted)(nil),     // 1: sem.middleware.planning.PlanningStarted
	(*PlanningIteration)(nil),   // 2: sem.middleware.planning.PlanningIteration
	(*PlanningReflection)(nil),  // 3: sem.middleware.planning.PlanningReflection
	(*PlanningCompleted)(nil),   // 4: sem.middleware.planning.PlanningCompleted
	(*PlanningTextStarted)(nil), // 5: sem.middleware.planning.PlanningTextStarted
	(*PlanningTextDelta)(nil),   // 6: sem.middleware.planning.PlanningTextDelta
	(*PlanningTextFinal)(nil),   // 7: sem.middleware.planning.PlanningTextFinal
	(*ExecutionStarted)(nil),    // 8: sem.middleware.planning.ExecutionStarted
	(*ExecutionCompleted)(nil),  // 9: sem.middleware.planning.ExecutionCompleted
	(*structpb.Struct)(nil),     // 10: google.protobuf.Struct
}
var file_proto_sem_middleware_planning_proto_depIdxs = []int32{
	0,  // 0: sem.middleware.planning.PlanningStarted.run:type_name -> sem.middleware.planning.PlanningRun
	0,  // 1: sem.middleware.planning.PlanningIteration.run:type_name -> sem.middleware.planning.PlanningRun
	10, // 2: sem.middleware.planning.PlanningIteration.extra:type_name -> google.protobuf.Struct
	0,  // 3: sem.middleware.planning.PlanningReflection.run:type_name -> sem.middleware.planning.PlanningRun
	0,  // 4: sem.middleware.planning.PlanningCompleted.run:type_name -> sem.middleware.planning.PlanningRun
	0,  // 5: sem.middleware.planning.PlanningTextStarted.run:type_name -> sem.middleware.planning.PlanningRun
	0,  // 6: sem.middleware.planning.PlanningTextDelta.run:type_name -> sem.middleware.planning.PlanningRun
	0,  // 7: sem.middleware.planning.PlanningTextFinal.run:type_name -> sem.middleware.planning.PlanningRun
	10, // 8: sem.middleware.planning.ExecutionCompleted.extra:type_name -> google.protobuf.Struct
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_sem_middleware_planning_proto_init() }
func file_proto_sem_middleware_planning_proto_init() {
	if File_proto_sem_middleware_planning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sem_middleware_planning_proto_rawDesc), len(file_proto_sem_middleware_planning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sem_middleware_planning_proto_goTypes,
		DependencyIndexes: file_proto_sem_middleware_planning_proto_depIdxs,
		MessageInfos:      file_proto_sem_middleware_planning_proto_msgTypes,
	}.Build()
	File_proto_sem_middleware_planning_proto = out.File
	file_proto_sem_middleware_planning_proto_goTypes = nil
	file_proto_sem_middleware_planning_proto_depIdxs = nil
}
