// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/sem/middleware/thinking_mode.proto

package middleware

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payload for thinking mode messages
type ThinkingModePayload struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Mode      string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Phase     string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Reasoning string                 `protobuf:"bytes,3,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	// Additional unstructured data from extractor
	ExtraData     *structpb.Struct `protobuf:"bytes,10,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkingModePayload) Reset() {
	*x = ThinkingModePayload{}
	mi := &file_proto_sem_middleware_thinking_mode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkingModePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkingModePayload) ProtoMessage() {}

func (x *ThinkingModePayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_middleware_thinking_mode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkingModePayload.ProtoReflect.Descriptor instead.
func (*ThinkingModePayload) Descriptor() ([]byte, []int) {
	return file_proto_sem_middleware_thinking_mode_proto_rawDescGZIP(), []int{0}
}

func (x *ThinkingModePayload) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ThinkingModePayload) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ThinkingModePayload) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *ThinkingModePayload) GetExtraData() *structpb.Struct {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

type ThinkingModeStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Data          *ThinkingModePayload   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkingModeStarted) Reset() {
	*x = ThinkingModeStarted{}
	mi := &file_proto_sem_middleware_thinking_mode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkingModeStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkingModeStarted) ProtoMessage() {}

func (x *ThinkingModeStarted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_middleware_thinking_mode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkingModeStarted.ProtoReflect.Descriptor instead.
func (*ThinkingModeStarted) Descriptor() ([]byte, []int) {
	return file_proto_sem_middleware_thinking_mode_proto_rawDescGZIP(), []int{1}
}

func (x *ThinkingModeStarted) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ThinkingModeStarted) GetData() *ThinkingModePayload {
	if x != nil {
		return x.Data
	}
	return nil
}

type ThinkingModeUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Data          *ThinkingModePayload   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkingModeUpdate) Reset() {
	*x = ThinkingModeUpdate{}
	mi := &file_proto_sem_middleware_thinking_mode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkingModeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkingModeUpdate) ProtoMessage() {}

func (x *ThinkingModeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_middleware_thinking_mode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkingModeUpdate.ProtoReflect.Descriptor instead.
func (*ThinkingModeUpdate) Descriptor() ([]byte, []int) {
	return file_proto_sem_middleware_thinking_mode_proto_rawDescGZIP(), []int{2}
}

func (x *ThinkingModeUpdate) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ThinkingModeUpdate) GetData() *ThinkingModePayload {
	if x != nil {
		return x.Data
	}
	return nil
}

type ThinkingModeCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Data          *ThinkingModePayload   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkingModeCompleted) Reset() {
	*x = ThinkingModeCompleted{}
	mi := &file_proto_sem_middleware_thinking_mode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkingModeCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkingModeCompleted) ProtoMessage() {}

func (x *ThinkingModeCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sem_middleware_thinking_mode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkingModeCompleted.ProtoReflect.Descriptor instead.
func (*ThinkingModeCompleted) Descriptor() ([]byte, []int) {
	return file_proto_sem_middleware_thinking_mode_proto_rawDescGZIP(), []int{3}
}

func (x *ThinkingModeCompleted) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ThinkingModeCompleted) GetData() *ThinkingModePayload {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ThinkingModeCompleted) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ThinkingModeCompleted) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_sem_middleware_thinking_mode_proto protoreflect.FileDescriptor

const file_proto_sem_middleware_thinking_mode_proto_rawDesc = "" +
	"\n" +
	"(proto/sem/middleware/thinking_mode.proto\x12\x1csem.middleware.thinking_mode\x1a\x1cgoogle/protobuf/struct.proto\"\x95\x01\n" +
	"\x13ThinkingModePayload\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x1c\n" +
	"\treasoning\x18\x03 \x01(\tR\treasoning\x126\n" +
	"\n" +
	"extra_data\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\textraData\"u\n" +
	"\x13ThinkingModeStarted\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12E\n" +
	"\x04data\x18\x02 \x01(\v21.sem.middleware.thinking_mode.ThinkingModePayloadR\x04data\"t\n" +
	"\x12ThinkingModeUpdate\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12E\n" +
	"\x04data\x18\x02 \x01(\v21.sem.middleware.thinking_mode.ThinkingModePayloadR\x04data\"\xa7\x01\n" +
	"\x15ThinkingModeCompleted\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12E\n" +
	"\x04data\x18\x02 \x01(\v21.sem.middleware.thinking_mode.ThinkingModePayloadR\x04data\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05errorBNZLgithub.com/go-go-golems/pinocchio/pkg/sem/pb/proto/sem/middleware;middlewareb\x06proto3"

var (
	file_proto_sem_middleware_thinking_mode_proto_rawDescOnce sync.Once
	file_proto_sem_middleware_thinking_mode_proto_rawDescData []byte
)

func file_proto_sem_middleware_thinking_mode_proto_rawDescGZIP() []byte {
	file_proto_sem_middleware_thinking_mode_proto_rawDescOnce.Do(func() {
		file_proto_sem_middleware_thinking_mode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sem_middleware_thinking_mode_proto_rawDesc), len(file_proto_sem_middleware_thinking_mode_proto_rawDesc)))
	})
	return file_proto_sem_middleware_thinking_mode_proto_rawDescData
}

var file_proto_sem_middleware_thinking_mode_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_sem_middleware_thinking_mode_proto_goTypes = []any{
	(*ThinkingModePayload)(nil),   // 0: sem.middleware.thinking_mode.ThinkingModePayload
	(*ThinkingModeStarted)(nil),   // 1: sem.middleware.thinking_mode.ThinkingModeStarted
	(*ThinkingModeUpdate)(nil),    // 2: sem.middleware.thinking_mode.ThinkingModeUpdate
	(*ThinkingModeCompleted)(nil), // 3: sem.middleware.thinking_mode.ThinkingModeCompleted
	(*structpb.Struct)(nil),       // 4: google.protobuf.Struct
}
var file_proto_sem_middleware_thinking_mode_proto_depIdxs = []int32{
	4, // 0: sem.middleware.thinking_mode.ThinkingModePayload.extra_data:type_name -> google.protobuf.Struct
	0, // 1: sem.middleware.thinking_mode.ThinkingModeStarted.data:type_name -> sem.middleware.thinking_mode.ThinkingModePayload
	0, // 2: sem.middleware.thinking_mode.ThinkingModeUpdate.data:type_name -> sem.middleware.thinking_mode.ThinkingModePayload
	0, // 3: sem.middleware.thinking_mode.ThinkingModeCompleted.data:type_name -> sem.middleware.thinking_mode.ThinkingModePayload
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_sem_middleware_thinking_mode_proto_init() }
func file_proto_sem_middleware_thinking_mode_proto_init() {
	if File_proto_sem_middleware_thinking_mode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sem_middleware_thinking_mode_proto_rawDesc), len(file_proto_sem_middleware_thinking_mode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sem_middleware_thinking_mode_proto_goTypes,
		DependencyIndexes: file_proto_sem_middleware_thinking_mode_proto_depIdxs,
		MessageInfos:      file_proto_sem_middleware_thinking_mode_proto_msgTypes,
	}.Build()
	File_proto_sem_middleware_thinking_mode_proto = out.File
	file_proto_sem_middleware_thinking_mode_proto_goTypes = nil
	file_proto_sem_middleware_thinking_mode_proto_depIdxs = nil
}
