// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file proto/sem/domain/team_analysis.proto (package sem.domain.team_analysis, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/sem/domain/team_analysis.proto.
 */
export const file_proto_sem_domain_team_analysis: GenFile = /*@__PURE__*/
  fileDesc("CiRwcm90by9zZW0vZG9tYWluL3RlYW1fYW5hbHlzaXMucHJvdG8SGHNlbS5kb21haW4udGVhbV9hbmFseXNpcyJKChFUZWFtQW5hbHlzaXNTdGFydBITCgthbmFseXNpc19pZBgBIAEoCRIRCgl0ZWFtX3NpemUYAiABKAUSDQoFZGVwdGgYAyABKAkicgoUVGVhbUFuYWx5c2lzUHJvZ3Jlc3MSEwoLYW5hbHlzaXNfaWQYASABKAkSEQoJYW5hbHl6aW5nGAIgASgJEhAKCHByb2dyZXNzGAMgASgBEhEKCXByb2Nlc3NlZBgEIAEoBRINCgV0b3RhbBgFIAEoBSK4AwoSVGVhbUFuYWx5c2lzUmVzdWx0EhMKC2FuYWx5c2lzX2lkGAEgASgJEhUKDW5ldHdvcmtfc2NvcmUYAiABKAESEAoIaW5zaWdodHMYAyADKAkSWgoSdmlzdWFsaXphdGlvbl9kYXRhGAogASgLMj4uc2VtLmRvbWFpbi50ZWFtX2FuYWx5c2lzLlRlYW1BbmFseXNpc1Jlc3VsdC5WaXN1YWxpemF0aW9uRGF0YRohCgROb2RlEgoKAmlkGAEgASgJEg0KBWxhYmVsGAIgASgJGksKBEVkZ2USDgoGc291cmNlGAEgASgJEg4KBnRhcmdldBgCIAEoCRIQCghzdHJlbmd0aBgDIAEoARIRCglzZW50aW1lbnQYBCABKAkalwEKEVZpc3VhbGl6YXRpb25EYXRhEkAKBW5vZGVzGAEgAygLMjEuc2VtLmRvbWFpbi50ZWFtX2FuYWx5c2lzLlRlYW1BbmFseXNpc1Jlc3VsdC5Ob2RlEkAKBWVkZ2VzGAIgAygLMjEuc2VtLmRvbWFpbi50ZWFtX2FuYWx5c2lzLlRlYW1BbmFseXNpc1Jlc3VsdC5FZGdlQkZaRGdpdGh1Yi5jb20vZ28tZ28tZ29sZW1zL3Bpbm9jY2hpby9wa2cvc2VtL3BiL3Byb3RvL3NlbS9kb21haW47ZG9tYWluYgZwcm90bzM");

/**
 * @generated from message sem.domain.team_analysis.TeamAnalysisStart
 */
export type TeamAnalysisStart = Message<"sem.domain.team_analysis.TeamAnalysisStart"> & {
  /**
   * @generated from field: string analysis_id = 1;
   */
  analysisId: string;

  /**
   * @generated from field: int32 team_size = 2;
   */
  teamSize: number;

  /**
   * @generated from field: string depth = 3;
   */
  depth: string;
};

/**
 * Describes the message sem.domain.team_analysis.TeamAnalysisStart.
 * Use `create(TeamAnalysisStartSchema)` to create a new message.
 */
export const TeamAnalysisStartSchema: GenMessage<TeamAnalysisStart> = /*@__PURE__*/
  messageDesc(file_proto_sem_domain_team_analysis, 0);

/**
 * @generated from message sem.domain.team_analysis.TeamAnalysisProgress
 */
export type TeamAnalysisProgress = Message<"sem.domain.team_analysis.TeamAnalysisProgress"> & {
  /**
   * @generated from field: string analysis_id = 1;
   */
  analysisId: string;

  /**
   * @generated from field: string analyzing = 2;
   */
  analyzing: string;

  /**
   * @generated from field: double progress = 3;
   */
  progress: number;

  /**
   * @generated from field: int32 processed = 4;
   */
  processed: number;

  /**
   * @generated from field: int32 total = 5;
   */
  total: number;
};

/**
 * Describes the message sem.domain.team_analysis.TeamAnalysisProgress.
 * Use `create(TeamAnalysisProgressSchema)` to create a new message.
 */
export const TeamAnalysisProgressSchema: GenMessage<TeamAnalysisProgress> = /*@__PURE__*/
  messageDesc(file_proto_sem_domain_team_analysis, 1);

/**
 * @generated from message sem.domain.team_analysis.TeamAnalysisResult
 */
export type TeamAnalysisResult = Message<"sem.domain.team_analysis.TeamAnalysisResult"> & {
  /**
   * @generated from field: string analysis_id = 1;
   */
  analysisId: string;

  /**
   * @generated from field: double network_score = 2;
   */
  networkScore: number;

  /**
   * @generated from field: repeated string insights = 3;
   */
  insights: string[];

  /**
   * @generated from field: sem.domain.team_analysis.TeamAnalysisResult.VisualizationData visualization_data = 10;
   */
  visualizationData?: TeamAnalysisResult_VisualizationData;
};

/**
 * Describes the message sem.domain.team_analysis.TeamAnalysisResult.
 * Use `create(TeamAnalysisResultSchema)` to create a new message.
 */
export const TeamAnalysisResultSchema: GenMessage<TeamAnalysisResult> = /*@__PURE__*/
  messageDesc(file_proto_sem_domain_team_analysis, 2);

/**
 * @generated from message sem.domain.team_analysis.TeamAnalysisResult.Node
 */
export type TeamAnalysisResult_Node = Message<"sem.domain.team_analysis.TeamAnalysisResult.Node"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string label = 2;
   */
  label: string;
};

/**
 * Describes the message sem.domain.team_analysis.TeamAnalysisResult.Node.
 * Use `create(TeamAnalysisResult_NodeSchema)` to create a new message.
 */
export const TeamAnalysisResult_NodeSchema: GenMessage<TeamAnalysisResult_Node> = /*@__PURE__*/
  messageDesc(file_proto_sem_domain_team_analysis, 2, 0);

/**
 * @generated from message sem.domain.team_analysis.TeamAnalysisResult.Edge
 */
export type TeamAnalysisResult_Edge = Message<"sem.domain.team_analysis.TeamAnalysisResult.Edge"> & {
  /**
   * @generated from field: string source = 1;
   */
  source: string;

  /**
   * @generated from field: string target = 2;
   */
  target: string;

  /**
   * @generated from field: double strength = 3;
   */
  strength: number;

  /**
   * @generated from field: string sentiment = 4;
   */
  sentiment: string;
};

/**
 * Describes the message sem.domain.team_analysis.TeamAnalysisResult.Edge.
 * Use `create(TeamAnalysisResult_EdgeSchema)` to create a new message.
 */
export const TeamAnalysisResult_EdgeSchema: GenMessage<TeamAnalysisResult_Edge> = /*@__PURE__*/
  messageDesc(file_proto_sem_domain_team_analysis, 2, 1);

/**
 * @generated from message sem.domain.team_analysis.TeamAnalysisResult.VisualizationData
 */
export type TeamAnalysisResult_VisualizationData = Message<"sem.domain.team_analysis.TeamAnalysisResult.VisualizationData"> & {
  /**
   * @generated from field: repeated sem.domain.team_analysis.TeamAnalysisResult.Node nodes = 1;
   */
  nodes: TeamAnalysisResult_Node[];

  /**
   * @generated from field: repeated sem.domain.team_analysis.TeamAnalysisResult.Edge edges = 2;
   */
  edges: TeamAnalysisResult_Edge[];
};

/**
 * Describes the message sem.domain.team_analysis.TeamAnalysisResult.VisualizationData.
 * Use `create(TeamAnalysisResult_VisualizationDataSchema)` to create a new message.
 */
export const TeamAnalysisResult_VisualizationDataSchema: GenMessage<TeamAnalysisResult_VisualizationData> = /*@__PURE__*/
  messageDesc(file_proto_sem_domain_team_analysis, 2, 2);

