// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/pinocchio/chatapp/v1/chat.proto

package chatappv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartInferenceCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Prompt         string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	RequestId      string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartInferenceCommand) Reset() {
	*x = StartInferenceCommand{}
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInferenceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInferenceCommand) ProtoMessage() {}

func (x *StartInferenceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInferenceCommand.ProtoReflect.Descriptor instead.
func (*StartInferenceCommand) Descriptor() ([]byte, []int) {
	return file_proto_pinocchio_chatapp_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *StartInferenceCommand) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *StartInferenceCommand) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *StartInferenceCommand) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type StopInferenceCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopInferenceCommand) Reset() {
	*x = StopInferenceCommand{}
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopInferenceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopInferenceCommand) ProtoMessage() {}

func (x *StopInferenceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopInferenceCommand.ProtoReflect.Descriptor instead.
func (*StopInferenceCommand) Descriptor() ([]byte, []int) {
	return file_proto_pinocchio_chatapp_v1_chat_proto_rawDescGZIP(), []int{1}
}

type ChatMessageUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Role            string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Prompt          string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Chunk           string                 `protobuf:"bytes,4,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Text            string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Content         string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Streaming       bool                   `protobuf:"varint,8,opt,name=streaming,proto3" json:"streaming,omitempty"`
	Error           string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	ParentMessageId string                 `protobuf:"bytes,10,opt,name=parent_message_id,json=parentMessageId,proto3" json:"parent_message_id,omitempty"`
	Segment         int32                  `protobuf:"varint,11,opt,name=segment,proto3" json:"segment,omitempty"`
	SegmentType     string                 `protobuf:"bytes,12,opt,name=segment_type,json=segmentType,proto3" json:"segment_type,omitempty"`
	Final           bool                   `protobuf:"varint,13,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatMessageUpdate) Reset() {
	*x = ChatMessageUpdate{}
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageUpdate) ProtoMessage() {}

func (x *ChatMessageUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageUpdate.ProtoReflect.Descriptor instead.
func (*ChatMessageUpdate) Descriptor() ([]byte, []int) {
	return file_proto_pinocchio_chatapp_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessageUpdate) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessageUpdate) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessageUpdate) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ChatMessageUpdate) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

func (x *ChatMessageUpdate) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessageUpdate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessageUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ChatMessageUpdate) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *ChatMessageUpdate) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ChatMessageUpdate) GetParentMessageId() string {
	if x != nil {
		return x.ParentMessageId
	}
	return ""
}

func (x *ChatMessageUpdate) GetSegment() int32 {
	if x != nil {
		return x.Segment
	}
	return 0
}

func (x *ChatMessageUpdate) GetSegmentType() string {
	if x != nil {
		return x.SegmentType
	}
	return ""
}

func (x *ChatMessageUpdate) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

type ChatMessageEntity struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Role            string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Prompt          string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Text            string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Content         string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Streaming       bool                   `protobuf:"varint,7,opt,name=streaming,proto3" json:"streaming,omitempty"`
	Error           string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	ParentMessageId string                 `protobuf:"bytes,9,opt,name=parent_message_id,json=parentMessageId,proto3" json:"parent_message_id,omitempty"`
	Segment         int32                  `protobuf:"varint,10,opt,name=segment,proto3" json:"segment,omitempty"`
	SegmentType     string                 `protobuf:"bytes,11,opt,name=segment_type,json=segmentType,proto3" json:"segment_type,omitempty"`
	Final           bool                   `protobuf:"varint,12,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatMessageEntity) Reset() {
	*x = ChatMessageEntity{}
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageEntity) ProtoMessage() {}

func (x *ChatMessageEntity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageEntity.ProtoReflect.Descriptor instead.
func (*ChatMessageEntity) Descriptor() ([]byte, []int) {
	return file_proto_pinocchio_chatapp_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMessageEntity) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessageEntity) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessageEntity) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ChatMessageEntity) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessageEntity) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessageEntity) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ChatMessageEntity) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *ChatMessageEntity) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ChatMessageEntity) GetParentMessageId() string {
	if x != nil {
		return x.ParentMessageId
	}
	return ""
}

func (x *ChatMessageEntity) GetSegment() int32 {
	if x != nil {
		return x.Segment
	}
	return 0
}

func (x *ChatMessageEntity) GetSegmentType() string {
	if x != nil {
		return x.SegmentType
	}
	return ""
}

func (x *ChatMessageEntity) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

type ReasoningUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ParentMessageId string                 `protobuf:"bytes,2,opt,name=parent_message_id,json=parentMessageId,proto3" json:"parent_message_id,omitempty"`
	Segment         int32                  `protobuf:"varint,3,opt,name=segment,proto3" json:"segment,omitempty"`
	Role            string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Chunk           string                 `protobuf:"bytes,5,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Text            string                 `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	Content         string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Streaming       bool                   `protobuf:"varint,9,opt,name=streaming,proto3" json:"streaming,omitempty"`
	Source          string                 `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	SegmentType     string                 `protobuf:"bytes,11,opt,name=segment_type,json=segmentType,proto3" json:"segment_type,omitempty"`
	Provider        string                 `protobuf:"bytes,12,opt,name=provider,proto3" json:"provider,omitempty"`
	ResponseId      string                 `protobuf:"bytes,13,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	ItemId          string                 `protobuf:"bytes,14,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	OutputIndex     *int32                 `protobuf:"varint,15,opt,name=output_index,json=outputIndex,proto3,oneof" json:"output_index,omitempty"`
	SummaryIndex    *int32                 `protobuf:"varint,16,opt,name=summary_index,json=summaryIndex,proto3,oneof" json:"summary_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReasoningUpdate) Reset() {
	*x = ReasoningUpdate{}
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningUpdate) ProtoMessage() {}

func (x *ReasoningUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningUpdate.ProtoReflect.Descriptor instead.
func (*ReasoningUpdate) Descriptor() ([]byte, []int) {
	return file_proto_pinocchio_chatapp_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ReasoningUpdate) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ReasoningUpdate) GetParentMessageId() string {
	if x != nil {
		return x.ParentMessageId
	}
	return ""
}

func (x *ReasoningUpdate) GetSegment() int32 {
	if x != nil {
		return x.Segment
	}
	return 0
}

func (x *ReasoningUpdate) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ReasoningUpdate) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

func (x *ReasoningUpdate) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ReasoningUpdate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReasoningUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReasoningUpdate) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *ReasoningUpdate) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ReasoningUpdate) GetSegmentType() string {
	if x != nil {
		return x.SegmentType
	}
	return ""
}

func (x *ReasoningUpdate) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ReasoningUpdate) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

func (x *ReasoningUpdate) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ReasoningUpdate) GetOutputIndex() int32 {
	if x != nil && x.OutputIndex != nil {
		return *x.OutputIndex
	}
	return 0
}

func (x *ReasoningUpdate) GetSummaryIndex() int32 {
	if x != nil && x.SummaryIndex != nil {
		return *x.SummaryIndex
	}
	return 0
}

type AgentModePreviewUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CandidateMode string                 `protobuf:"bytes,2,opt,name=candidate_mode,json=candidateMode,proto3" json:"candidate_mode,omitempty"`
	Analysis      string                 `protobuf:"bytes,3,opt,name=analysis,proto3" json:"analysis,omitempty"`
	ParseState    string                 `protobuf:"bytes,4,opt,name=parse_state,json=parseState,proto3" json:"parse_state,omitempty"`
	Preview       bool                   `protobuf:"varint,5,opt,name=preview,proto3" json:"preview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentModePreviewUpdate) Reset() {
	*x = AgentModePreviewUpdate{}
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentModePreviewUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentModePreviewUpdate) ProtoMessage() {}

func (x *AgentModePreviewUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentModePreviewUpdate.ProtoReflect.Descriptor instead.
func (*AgentModePreviewUpdate) Descriptor() ([]byte, []int) {
	return file_proto_pinocchio_chatapp_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *AgentModePreviewUpdate) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AgentModePreviewUpdate) GetCandidateMode() string {
	if x != nil {
		return x.CandidateMode
	}
	return ""
}

func (x *AgentModePreviewUpdate) GetAnalysis() string {
	if x != nil {
		return x.Analysis
	}
	return ""
}

func (x *AgentModePreviewUpdate) GetParseState() string {
	if x != nil {
		return x.ParseState
	}
	return ""
}

func (x *AgentModePreviewUpdate) GetPreview() bool {
	if x != nil {
		return x.Preview
	}
	return false
}

type AgentModeCommittedUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Analysis      string                 `protobuf:"bytes,5,opt,name=analysis,proto3" json:"analysis,omitempty"`
	Preview       bool                   `protobuf:"varint,6,opt,name=preview,proto3" json:"preview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentModeCommittedUpdate) Reset() {
	*x = AgentModeCommittedUpdate{}
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentModeCommittedUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentModeCommittedUpdate) ProtoMessage() {}

func (x *AgentModeCommittedUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentModeCommittedUpdate.ProtoReflect.Descriptor instead.
func (*AgentModeCommittedUpdate) Descriptor() ([]byte, []int) {
	return file_proto_pinocchio_chatapp_v1_chat_proto_rawDescGZIP(), []int{6}
}

func (x *AgentModeCommittedUpdate) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AgentModeCommittedUpdate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AgentModeCommittedUpdate) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *AgentModeCommittedUpdate) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *AgentModeCommittedUpdate) GetAnalysis() string {
	if x != nil {
		return x.Analysis
	}
	return ""
}

func (x *AgentModeCommittedUpdate) GetPreview() bool {
	if x != nil {
		return x.Preview
	}
	return false
}

type AgentModePreviewCleared struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentModePreviewCleared) Reset() {
	*x = AgentModePreviewCleared{}
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentModePreviewCleared) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentModePreviewCleared) ProtoMessage() {}

func (x *AgentModePreviewCleared) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentModePreviewCleared.ProtoReflect.Descriptor instead.
func (*AgentModePreviewCleared) Descriptor() ([]byte, []int) {
	return file_proto_pinocchio_chatapp_v1_chat_proto_rawDescGZIP(), []int{7}
}

func (x *AgentModePreviewCleared) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type AgentModeEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Analysis      string                 `protobuf:"bytes,5,opt,name=analysis,proto3" json:"analysis,omitempty"`
	Preview       bool                   `protobuf:"varint,6,opt,name=preview,proto3" json:"preview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentModeEntity) Reset() {
	*x = AgentModeEntity{}
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentModeEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentModeEntity) ProtoMessage() {}

func (x *AgentModeEntity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentModeEntity.ProtoReflect.Descriptor instead.
func (*AgentModeEntity) Descriptor() ([]byte, []int) {
	return file_proto_pinocchio_chatapp_v1_chat_proto_rawDescGZIP(), []int{8}
}

func (x *AgentModeEntity) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AgentModeEntity) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AgentModeEntity) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *AgentModeEntity) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *AgentModeEntity) GetAnalysis() string {
	if x != nil {
		return x.Analysis
	}
	return ""
}

func (x *AgentModeEntity) GetPreview() bool {
	if x != nil {
		return x.Preview
	}
	return false
}

type ToolCallUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,2,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Input         string                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	Executing     bool                   `protobuf:"varint,5,opt,name=executing,proto3" json:"executing,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallUpdate) Reset() {
	*x = ToolCallUpdate{}
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallUpdate) ProtoMessage() {}

func (x *ToolCallUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallUpdate.ProtoReflect.Descriptor instead.
func (*ToolCallUpdate) Descriptor() ([]byte, []int) {
	return file_proto_pinocchio_chatapp_v1_chat_proto_rawDescGZIP(), []int{9}
}

func (x *ToolCallUpdate) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ToolCallUpdate) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolCallUpdate) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallUpdate) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *ToolCallUpdate) GetExecuting() bool {
	if x != nil {
		return x.Executing
	}
	return false
}

func (x *ToolCallUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ToolResultUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,2,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Result        string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResultUpdate) Reset() {
	*x = ToolResultUpdate{}
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultUpdate) ProtoMessage() {}

func (x *ToolResultUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResultUpdate.ProtoReflect.Descriptor instead.
func (*ToolResultUpdate) Descriptor() ([]byte, []int) {
	return file_proto_pinocchio_chatapp_v1_chat_proto_rawDescGZIP(), []int{10}
}

func (x *ToolResultUpdate) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ToolResultUpdate) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolResultUpdate) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolResultUpdate) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolResultUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ToolCallEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,2,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Input         string                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	Executing     bool                   `protobuf:"varint,5,opt,name=executing,proto3" json:"executing,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallEntity) Reset() {
	*x = ToolCallEntity{}
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallEntity) ProtoMessage() {}

func (x *ToolCallEntity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallEntity.ProtoReflect.Descriptor instead.
func (*ToolCallEntity) Descriptor() ([]byte, []int) {
	return file_proto_pinocchio_chatapp_v1_chat_proto_rawDescGZIP(), []int{11}
}

func (x *ToolCallEntity) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ToolCallEntity) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolCallEntity) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallEntity) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *ToolCallEntity) GetExecuting() bool {
	if x != nil {
		return x.Executing
	}
	return false
}

func (x *ToolCallEntity) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ToolResultEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,2,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Result        string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResultEntity) Reset() {
	*x = ToolResultEntity{}
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultEntity) ProtoMessage() {}

func (x *ToolResultEntity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResultEntity.ProtoReflect.Descriptor instead.
func (*ToolResultEntity) Descriptor() ([]byte, []int) {
	return file_proto_pinocchio_chatapp_v1_chat_proto_rawDescGZIP(), []int{12}
}

func (x *ToolResultEntity) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ToolResultEntity) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolResultEntity) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolResultEntity) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolResultEntity) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_pinocchio_chatapp_v1_chat_proto protoreflect.FileDescriptor

const file_proto_pinocchio_chatapp_v1_chat_proto_rawDesc = "" +
	"\n" +
	"%proto/pinocchio/chatapp/v1/chat.proto\x12\x14pinocchio.chatapp.v1\"w\n" +
	"\x15StartInferenceCommand\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"\x16\n" +
	"\x14StopInferenceCommand\"\xed\x02\n" +
	"\x11ChatMessageUpdate\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05chunk\x18\x04 \x01(\tR\x05chunk\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1c\n" +
	"\tstreaming\x18\b \x01(\bR\tstreaming\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x12*\n" +
	"\x11parent_message_id\x18\n" +
	" \x01(\tR\x0fparentMessageId\x12\x18\n" +
	"\asegment\x18\v \x01(\x05R\asegment\x12!\n" +
	"\fsegment_type\x18\f \x01(\tR\vsegmentType\x12\x14\n" +
	"\x05final\x18\r \x01(\bR\x05final\"\xd7\x02\n" +
	"\x11ChatMessageEntity\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1c\n" +
	"\tstreaming\x18\a \x01(\bR\tstreaming\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12*\n" +
	"\x11parent_message_id\x18\t \x01(\tR\x0fparentMessageId\x12\x18\n" +
	"\asegment\x18\n" +
	" \x01(\x05R\asegment\x12!\n" +
	"\fsegment_type\x18\v \x01(\tR\vsegmentType\x12\x14\n" +
	"\x05final\x18\f \x01(\bR\x05final\"\x8a\x04\n" +
	"\x0fReasoningUpdate\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12*\n" +
	"\x11parent_message_id\x18\x02 \x01(\tR\x0fparentMessageId\x12\x18\n" +
	"\asegment\x18\x03 \x01(\x05R\asegment\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x14\n" +
	"\x05chunk\x18\x05 \x01(\tR\x05chunk\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1c\n" +
	"\tstreaming\x18\t \x01(\bR\tstreaming\x12\x16\n" +
	"\x06source\x18\n" +
	" \x01(\tR\x06source\x12!\n" +
	"\fsegment_type\x18\v \x01(\tR\vsegmentType\x12\x1a\n" +
	"\bprovider\x18\f \x01(\tR\bprovider\x12\x1f\n" +
	"\vresponse_id\x18\r \x01(\tR\n" +
	"responseId\x12\x17\n" +
	"\aitem_id\x18\x0e \x01(\tR\x06itemId\x12&\n" +
	"\foutput_index\x18\x0f \x01(\x05H\x00R\voutputIndex\x88\x01\x01\x12(\n" +
	"\rsummary_index\x18\x10 \x01(\x05H\x01R\fsummaryIndex\x88\x01\x01B\x0f\n" +
	"\r_output_indexB\x10\n" +
	"\x0e_summary_index\"\xb5\x01\n" +
	"\x16AgentModePreviewUpdate\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12%\n" +
	"\x0ecandidate_mode\x18\x02 \x01(\tR\rcandidateMode\x12\x1a\n" +
	"\banalysis\x18\x03 \x01(\tR\banalysis\x12\x1f\n" +
	"\vparse_state\x18\x04 \x01(\tR\n" +
	"parseState\x12\x18\n" +
	"\apreview\x18\x05 \x01(\bR\apreview\"\xa9\x01\n" +
	"\x18AgentModeCommittedUpdate\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12\x1a\n" +
	"\banalysis\x18\x05 \x01(\tR\banalysis\x12\x18\n" +
	"\apreview\x18\x06 \x01(\bR\apreview\"8\n" +
	"\x17AgentModePreviewCleared\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"\xa0\x01\n" +
	"\x0fAgentModeEntity\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12\x1a\n" +
	"\banalysis\x18\x05 \x01(\tR\banalysis\x12\x18\n" +
	"\apreview\x18\x06 \x01(\bR\apreview\"\xba\x01\n" +
	"\x0eToolCallUpdate\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12 \n" +
	"\ftool_call_id\x18\x02 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x14\n" +
	"\x05input\x18\x04 \x01(\tR\x05input\x12\x1c\n" +
	"\texecuting\x18\x05 \x01(\bR\texecuting\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\xa0\x01\n" +
	"\x10ToolResultUpdate\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12 \n" +
	"\ftool_call_id\x18\x02 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\xba\x01\n" +
	"\x0eToolCallEntity\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12 \n" +
	"\ftool_call_id\x18\x02 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x14\n" +
	"\x05input\x18\x04 \x01(\tR\x05input\x12\x1c\n" +
	"\texecuting\x18\x05 \x01(\bR\texecuting\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\xa0\x01\n" +
	"\x10ToolResultEntity\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12 \n" +
	"\ftool_call_id\x18\x02 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06statusBWZUgithub.com/go-go-golems/pinocchio/pkg/chatapp/pb/proto/pinocchio/chatapp/v1;chatappv1b\x06proto3"

var (
	file_proto_pinocchio_chatapp_v1_chat_proto_rawDescOnce sync.Once
	file_proto_pinocchio_chatapp_v1_chat_proto_rawDescData []byte
)

func file_proto_pinocchio_chatapp_v1_chat_proto_rawDescGZIP() []byte {
	file_proto_pinocchio_chatapp_v1_chat_proto_rawDescOnce.Do(func() {
		file_proto_pinocchio_chatapp_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pinocchio_chatapp_v1_chat_proto_rawDesc), len(file_proto_pinocchio_chatapp_v1_chat_proto_rawDesc)))
	})
	return file_proto_pinocchio_chatapp_v1_chat_proto_rawDescData
}

var file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_pinocchio_chatapp_v1_chat_proto_goTypes = []any{
	(*StartInferenceCommand)(nil),    // 0: pinocchio.chatapp.v1.StartInferenceCommand
	(*StopInferenceCommand)(nil),     // 1: pinocchio.chatapp.v1.StopInferenceCommand
	(*ChatMessageUpdate)(nil),        // 2: pinocchio.chatapp.v1.ChatMessageUpdate
	(*ChatMessageEntity)(nil),        // 3: pinocchio.chatapp.v1.ChatMessageEntity
	(*ReasoningUpdate)(nil),          // 4: pinocchio.chatapp.v1.ReasoningUpdate
	(*AgentModePreviewUpdate)(nil),   // 5: pinocchio.chatapp.v1.AgentModePreviewUpdate
	(*AgentModeCommittedUpdate)(nil), // 6: pinocchio.chatapp.v1.AgentModeCommittedUpdate
	(*AgentModePreviewCleared)(nil),  // 7: pinocchio.chatapp.v1.AgentModePreviewCleared
	(*AgentModeEntity)(nil),          // 8: pinocchio.chatapp.v1.AgentModeEntity
	(*ToolCallUpdate)(nil),           // 9: pinocchio.chatapp.v1.ToolCallUpdate
	(*ToolResultUpdate)(nil),         // 10: pinocchio.chatapp.v1.ToolResultUpdate
	(*ToolCallEntity)(nil),           // 11: pinocchio.chatapp.v1.ToolCallEntity
	(*ToolResultEntity)(nil),         // 12: pinocchio.chatapp.v1.ToolResultEntity
}
var file_proto_pinocchio_chatapp_v1_chat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pinocchio_chatapp_v1_chat_proto_init() }
func file_proto_pinocchio_chatapp_v1_chat_proto_init() {
	if File_proto_pinocchio_chatapp_v1_chat_proto != nil {
		return
	}
	file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pinocchio_chatapp_v1_chat_proto_rawDesc), len(file_proto_pinocchio_chatapp_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_pinocchio_chatapp_v1_chat_proto_goTypes,
		DependencyIndexes: file_proto_pinocchio_chatapp_v1_chat_proto_depIdxs,
		MessageInfos:      file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes,
	}.Build()
	File_proto_pinocchio_chatapp_v1_chat_proto = out.File
	file_proto_pinocchio_chatapp_v1_chat_proto_goTypes = nil
	file_proto_pinocchio_chatapp_v1_chat_proto_depIdxs = nil
}
