// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/pinocchio/chatapp/v1/chat.proto

package chatappv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartInferenceCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Prompt         string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	RequestId      string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartInferenceCommand) Reset() {
	*x = StartInferenceCommand{}
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInferenceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInferenceCommand) ProtoMessage() {}

func (x *StartInferenceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInferenceCommand.ProtoReflect.Descriptor instead.
func (*StartInferenceCommand) Descriptor() ([]byte, []int) {
	return file_proto_pinocchio_chatapp_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *StartInferenceCommand) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *StartInferenceCommand) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *StartInferenceCommand) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type StopInferenceCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopInferenceCommand) Reset() {
	*x = StopInferenceCommand{}
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopInferenceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopInferenceCommand) ProtoMessage() {}

func (x *StopInferenceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopInferenceCommand.ProtoReflect.Descriptor instead.
func (*StopInferenceCommand) Descriptor() ([]byte, []int) {
	return file_proto_pinocchio_chatapp_v1_chat_proto_rawDescGZIP(), []int{1}
}

type ChatMessageUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Chunk         string                 `protobuf:"bytes,4,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Streaming     bool                   `protobuf:"varint,8,opt,name=streaming,proto3" json:"streaming,omitempty"`
	Error         string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessageUpdate) Reset() {
	*x = ChatMessageUpdate{}
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageUpdate) ProtoMessage() {}

func (x *ChatMessageUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageUpdate.ProtoReflect.Descriptor instead.
func (*ChatMessageUpdate) Descriptor() ([]byte, []int) {
	return file_proto_pinocchio_chatapp_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessageUpdate) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessageUpdate) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessageUpdate) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ChatMessageUpdate) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

func (x *ChatMessageUpdate) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessageUpdate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessageUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ChatMessageUpdate) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *ChatMessageUpdate) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ChatMessageEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Streaming     bool                   `protobuf:"varint,7,opt,name=streaming,proto3" json:"streaming,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessageEntity) Reset() {
	*x = ChatMessageEntity{}
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageEntity) ProtoMessage() {}

func (x *ChatMessageEntity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageEntity.ProtoReflect.Descriptor instead.
func (*ChatMessageEntity) Descriptor() ([]byte, []int) {
	return file_proto_pinocchio_chatapp_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMessageEntity) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessageEntity) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessageEntity) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ChatMessageEntity) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessageEntity) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessageEntity) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ChatMessageEntity) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *ChatMessageEntity) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_pinocchio_chatapp_v1_chat_proto protoreflect.FileDescriptor

const file_proto_pinocchio_chatapp_v1_chat_proto_rawDesc = "" +
	"\n" +
	"%proto/pinocchio/chatapp/v1/chat.proto\x12\x14pinocchio.chatapp.v1\"w\n" +
	"\x15StartInferenceCommand\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"\x16\n" +
	"\x14StopInferenceCommand\"\xee\x01\n" +
	"\x11ChatMessageUpdate\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05chunk\x18\x04 \x01(\tR\x05chunk\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1c\n" +
	"\tstreaming\x18\b \x01(\bR\tstreaming\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\"\xd8\x01\n" +
	"\x11ChatMessageEntity\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1c\n" +
	"\tstreaming\x18\a \x01(\bR\tstreaming\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05errorBQZOgithub.com/go-go-golems/pinocchio/pkg/chatapp/pb/pinocchio/chatapp/v1;chatappv1b\x06proto3"

var (
	file_proto_pinocchio_chatapp_v1_chat_proto_rawDescOnce sync.Once
	file_proto_pinocchio_chatapp_v1_chat_proto_rawDescData []byte
)

func file_proto_pinocchio_chatapp_v1_chat_proto_rawDescGZIP() []byte {
	file_proto_pinocchio_chatapp_v1_chat_proto_rawDescOnce.Do(func() {
		file_proto_pinocchio_chatapp_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pinocchio_chatapp_v1_chat_proto_rawDesc), len(file_proto_pinocchio_chatapp_v1_chat_proto_rawDesc)))
	})
	return file_proto_pinocchio_chatapp_v1_chat_proto_rawDescData
}

var file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_pinocchio_chatapp_v1_chat_proto_goTypes = []any{
	(*StartInferenceCommand)(nil), // 0: pinocchio.chatapp.v1.StartInferenceCommand
	(*StopInferenceCommand)(nil),  // 1: pinocchio.chatapp.v1.StopInferenceCommand
	(*ChatMessageUpdate)(nil),     // 2: pinocchio.chatapp.v1.ChatMessageUpdate
	(*ChatMessageEntity)(nil),     // 3: pinocchio.chatapp.v1.ChatMessageEntity
}
var file_proto_pinocchio_chatapp_v1_chat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pinocchio_chatapp_v1_chat_proto_init() }
func file_proto_pinocchio_chatapp_v1_chat_proto_init() {
	if File_proto_pinocchio_chatapp_v1_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pinocchio_chatapp_v1_chat_proto_rawDesc), len(file_proto_pinocchio_chatapp_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_pinocchio_chatapp_v1_chat_proto_goTypes,
		DependencyIndexes: file_proto_pinocchio_chatapp_v1_chat_proto_depIdxs,
		MessageInfos:      file_proto_pinocchio_chatapp_v1_chat_proto_msgTypes,
	}.Build()
	File_proto_pinocchio_chatapp_v1_chat_proto = out.File
	file_proto_pinocchio_chatapp_v1_chat_proto_goTypes = nil
	file_proto_pinocchio_chatapp_v1_chat_proto_depIdxs = nil
}
